package app.infiniterpg.game;

import android.content.Context;
import android.graphics.Bitmap;
import android.graphics.BitmapFactory;
import android.graphics.Canvas;
import android.graphics.Color;
import android.graphics.Paint;
import android.graphics.Rect;
import android.graphics.RectF;
import android.view.MotionEvent;
import android.view.View;
import org.json.JSONArray;
import org.json.JSONObject;
import app.infiniterpg.R;
import app.infiniterpg.ai.RuntimeSignals;
import app.infiniterpg.data.ContentItem;
import app.infiniterpg.data.ContentRepository;
import app.infiniterpg.data.MobState;
import app.infiniterpg.data.WorldStructure;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;

public final class GameView extends View {
    public interface Listener { void openChest(long structureId); }
    private static final long DAY_MS=15*60*1000L,NIGHT_MS=10*60*1000L,CYCLE_MS=DAY_MS+NIGHT_MS,WEATHER_MS=4*60*1000L;
    private final ContentRepository repo;private final Listener listener;private final Paint paint=new Paint(Paint.ANTI_ALIAS_FLAG),pixel=new Paint(Paint.ANTI_ALIAS_FLAG|Paint.FILTER_BITMAP_FLAG);
    private float playerX,playerY,insideX,insideY,insideLimitX=4.5f,insideLimitY=2.7f;private int health,energy;private final long seed,worldStart;private float joyX,joyY;private int joyPointer=-1,directionRow;private boolean walking,inside,insideCave;private long insideHouseId=-1,lastFrame=System.nanoTime(),lastSave,lastEntityLoad;private String toast="Explore, gather, build, and survive";private long toastUntil=System.currentTimeMillis()+5000;
    private boolean placing,hasClock;private String placeItemKey,placeType;private ContentItem placeBlueprint;private float placeX,placeY;
    private final Bitmap playerSheet,itemAtlas,buildAtlas,mobSheet,structureAtlas;private final WorldTextureCache worldTextures;private final Map<Long,Long> harvested=new HashMap<>();private final Map<String,ContentItem> creatureInfo=new HashMap<>(),structureInfo=new HashMap<>();private final Map<String,Bitmap> generatedMobSprites=new HashMap<>(),generatedStructureSprites=new HashMap<>();
    private List<ContentItem> materials=new ArrayList<>(),weather=new ArrayList<>();private List<WorldStructure> structures=new ArrayList<>();private List<MobState> mobs=new ArrayList<>();private WorldStructure insideStructure;
    private final List<Scenery> sceneryCache=new ArrayList<>();private int sceneryRegionX=Integer.MIN_VALUE,sceneryRegionY=Integer.MIN_VALUE,sceneryWidth,sceneryHeight;
    private static final class Scenery {final float x,y;final int kind,variant;final long hash;Scenery(float x,float y,int kind,int variant,long hash){this.x=x;this.y=y;this.kind=kind;this.variant=variant;this.hash=hash;}}

    public GameView(Context context,ContentRepository repo,Listener listener){super(context);this.repo=repo;this.listener=listener;double[] p=repo.loadPlayer();playerX=(float)p[0];playerY=(float)p[1];health=(int)p[2];energy=(int)p[3];seed=(long)p[4];worldStart=number(repo.getState("world_clock_start",Long.toString(System.currentTimeMillis())),System.currentTimeMillis());playerSheet=BitmapFactory.decodeResource(getResources(),R.drawable.player_sheet_v2);itemAtlas=BitmapFactory.decodeResource(getResources(),R.drawable.item_atlas_v2);buildAtlas=BitmapFactory.decodeResource(getResources(),R.drawable.buildables_atlas_v3);mobSheet=BitmapFactory.decodeResource(getResources(),R.drawable.passive_mobs_directional_v5);structureAtlas=BitmapFactory.decodeResource(getResources(),R.drawable.structures_caves_atlas_v5);worldTextures=new WorldTextureCache(context,repo,seed);paint.setTypeface(android.graphics.Typeface.create("sans",android.graphics.Typeface.BOLD));hasClock=repo.inventory("sunstone_clock")>0;reloadCatalog();setKeepScreenOn(true);}
    public void reloadCatalog(){ArrayList<ContentItem> gathered=new ArrayList<>();for(ContentItem m:repo.list("MATERIAL",256))if(!m.text("biome","").isEmpty())gathered.add(m);materials=gathered;weather=repo.list("WEATHER",64);creatureInfo.clear();generatedMobSprites.clear();for(ContentItem c:repo.list("CREATURE",128)){creatureInfo.put(c.identity,c);if(c.number("atlas_row",-1)<0){Bitmap b=PixelTexture.bitmap(c,96);if(b!=null)generatedMobSprites.put(c.identity,b);}}structureInfo.clear();generatedStructureSprites.clear();for(ContentItem s:repo.list("STRUCTURE",128)){structureInfo.put(s.identity,s);if(s.number("atlas_cell",-1)<0){Bitmap b=PixelTexture.bitmap(s,128);if(b!=null)generatedStructureSprites.put(s.identity,b);}}if(worldTextures!=null)worldTextures.reload();invalidate();}
    public void refreshWorld(){hasClock=repo.inventory("sunstone_clock")>0;lastEntityLoad=0;reloadEntities();invalidate();}
    @Override protected void onDraw(Canvas c){super.onDraw(c);long nowNanos=System.nanoTime(),now=System.currentTimeMillis();float dt=Math.min(.05f,(nowNanos-lastFrame)/1_000_000_000f);lastFrame=nowNanos;update(dt,now);if(inside){if(insideCave)drawCaveInterior(c,now);else drawInterior(c,now);}else{if(now-lastEntityLoad>4000)reloadEntities();drawWorld(c);drawScenery(c,now);drawStructures(c,now);drawResources(c);drawMobs(c,now);drawPlayer(c,getWidth()/2f,getHeight()/2f);if(placing)drawPlacement(c);drawAtmosphere(c,now);}drawHud(c,now);if(now-lastSave>5000){repo.savePlayer(playerX,playerY,health,energy);lastSave=now;}postInvalidateDelayed(32);}
    private void update(float dt,long now){float len=(float)Math.hypot(joyX,joyY);walking=len>.08f&&!placing;if(walking){if(Math.abs(joyX)>Math.abs(joyY))directionRow=joyX<0?1:2;else directionRow=joyY<0?3:0;float speed=inside?3.0f:3.4f,dx=joyX/Math.max(1,len)*speed*dt,dy=joyY/Math.max(1,len)*speed*dt;if(inside){insideX=Math.max(-insideLimitX,Math.min(insideLimitX,insideX+dx));insideY=Math.max(-insideLimitY,Math.min(insideLimitY,insideY+dy));}else{playerX+=dx;playerY+=dy;}RuntimeSignals.gameBusy();}for(MobState mob:mobs){if(mob.health<=0)continue;double phase=(now/1000.0+mob.id*.73);float pace=mob.isBaby(now)?.12f:.07f,dx=(float)Math.sin(phase*.61)*pace*dt,dy=(float)Math.cos(phase*.47)*pace*dt;mob.x+=dx;mob.y+=dy;mob.walking=Math.abs(dx)+Math.abs(dy)>.0005f;if(mob.walking){mob.walkPhase+=dt*5.5f;if(Math.abs(dx)>Math.abs(dy))mob.facing=dx<0?1:2;else mob.facing=dy<0?3:0;}}}
    private int tile(){return Math.max(30,Math.min(48,getHeight()/14));}
    private void reloadEntities(){if(inside)return;repo.ensureMobsAround(playerX,playerY,seed);repo.ensureCavesAround(playerX,playerY,seed);structures=repo.structuresNear(playerX,playerY,55);mobs=repo.nearbyMobs(playerX,playerY,38);sceneryRegionX=Integer.MIN_VALUE;lastEntityLoad=System.currentTimeMillis();}
    private void drawWorld(Canvas c){int t=tile(),chunk=t*WorldTextureCache.CHUNK_TILES;float cameraX=playerX*t-getWidth()/2f,cameraY=playerY*t-getHeight()/2f;int startX=(int)Math.floor(cameraX/chunk)-1,startY=(int)Math.floor(cameraY/chunk)-1,endX=(int)Math.ceil((cameraX+getWidth())/chunk)+1,endY=(int)Math.ceil((cameraY+getHeight())/chunk)+1;for(int cy=startY;cy<=endY;cy++)for(int cx=startX;cx<=endX;cx++){float left=cx*chunk-cameraX,top=cy*chunk-cameraY;c.drawBitmap(worldTextures.chunk(cx,cy),null,new RectF(left,top,left+chunk+1,top+chunk+1),pixel);}}
    private void drawScenery(Canvas c,long now){
        int t=tile();float camX=playerX*t-getWidth()/2f,camY=playerY*t-getHeight()/2f;
        int regionX=Math.floorDiv((int)Math.floor(playerX),4),regionY=Math.floorDiv((int)Math.floor(playerY),4);if(regionX!=sceneryRegionX||regionY!=sceneryRegionY||getWidth()!=sceneryWidth||getHeight()!=sceneryHeight)rebuildScenery(t,regionX,regionY);
        for(Scenery s:sceneryCache){float px=s.x*t-camX+t*.5f,py=s.y*t-camY+t*.5f;if(px<-t*3||px>getWidth()+t*3||py<-t*3||py>getHeight()+t*2)continue;if(s.kind==0)drawTree(c,px,py,t,s.variant,s.hash);else if(s.kind==1)drawShrub(c,px,py,t,s.variant,s.hash);else if(s.kind==2)drawFlowerPatch(c,px,py,t,s.hash);else drawRock(c,px,py,t,s.variant);}
        drawBirds(c,now);
    }
    private void rebuildScenery(int t,int regionX,int regionY){
        sceneryCache.clear();sceneryRegionX=regionX;sceneryRegionY=regionY;sceneryWidth=getWidth();sceneryHeight=getHeight();
        int minX=(int)Math.floor(playerX-getWidth()/(2f*t))-5,maxX=(int)Math.ceil(playerX+getWidth()/(2f*t))+5,minY=(int)Math.floor(playerY-getHeight()/(2f*t))-6,maxY=(int)Math.ceil(playerY+getHeight()/(2f*t))+5;
        // The lattice is aligned to absolute world coordinates. The old loop began at the
        // player's current tile, which changed parity while walking and made every tree jump.
        int startX=Math.floorDiv(minX,2)*2,startY=Math.floorDiv(minY,2)*2;
        for(int y=startY;y<=maxY;y+=2)for(int x=startX;x<=maxX;x+=2){
            long h=WorldMath.hash(seed^0xF10A55,x,y),region=WorldMath.hash(seed^0x71C57E2,Math.floorDiv(x,16),Math.floorDiv(y,16));
            float wx=x+1f+((((h>>>16)&1023)/1023f)-.5f)*1.45f,wy=y+1f+((((h>>>28)&1023)/1023f)-.5f)*1.45f;
            if(sceneryBlocked(wx,wy)||Math.abs(WorldMath.noise(seed^0x7A11,wx*.035,wy*.035)-.5)<.032)continue;
            int zone=(int)((region>>>9)&255),roll=(int)(h&255),variant=(int)((h>>>40)&3);
            int kind=-1;if(zone<88){if(roll<82)kind=0;else if(roll<124)kind=1;else if(roll<137)kind=3;else if(roll<154)kind=2;}
            else if(zone<172){if(roll<16)kind=0;else if(roll<49)kind=1;else if(roll<118)kind=2;else if(roll<130)kind=3;}
            else{if(roll<13)kind=0;else if(roll<70)kind=1;else if(roll<116)kind=3;else if(roll<140)kind=2;}
            if(kind>=0)sceneryCache.add(new Scenery(wx,wy,kind,variant,h));
        }
    }
    private boolean sceneryBlocked(float x,float y){if(Math.hypot(x,y)<3.5)return true;for(WorldStructure s:structures){float clearance="grand_lodge".equals(s.type)?4.4f:"timber_house".equals(s.type)?3.4f:"small_cabin".equals(s.type)?2.7f:1.7f;if(Math.hypot(x-s.x,y-s.y)<clearance)return true;}return false;}
    private void drawTree(Canvas c,float x,float base,int t,int variant,long h){
        float size=1.12f+((h>>>48)&255)/255f*.52f,trunkTop=base-t*(.93f+.16f*size),crownY=base-t*(1.20f+.12f*size),radius=t*(.53f+.13f*size);
        paint.setColor(Color.argb(62,8,22,16));c.drawOval(new RectF(x-radius*.72f,base-t*.10f,x+radius*.72f,base+t*.22f),paint);
        paint.setColor(variant==2?Color.rgb(184,169,125):variant==3?Color.rgb(92,60,42):Color.rgb(105,73,45));c.drawRoundRect(x-t*.13f*size,trunkTop,x+t*.13f*size,base+t*.10f,t*.07f,t*.07f,paint);
        paint.setStrokeWidth(Math.max(2,t*.065f));paint.setColor(variant==2?Color.rgb(116,105,77):Color.rgb(78,54,38));c.drawLine(x,trunkTop+t*.30f,x-radius*.48f,crownY+radius*.16f,paint);c.drawLine(x,trunkTop+t*.22f,x+radius*.45f,crownY+radius*.12f,paint);
        int dark=variant==1?Color.rgb(31,73,52):variant==2?Color.rgb(92,113,53):variant==3?Color.rgb(118,70,38):Color.rgb(35,91,48),mid=variant==1?Color.rgb(45,103,66):variant==2?Color.rgb(148,145,67):variant==3?Color.rgb(173,92,43):Color.rgb(55,126,60),light=variant==1?Color.rgb(68,132,81):variant==2?Color.rgb(188,169,76):variant==3?Color.rgb(211,123,53):Color.rgb(83,153,71);
        if(variant==1){paint.setColor(dark);c.drawOval(new RectF(x-radius*.62f,crownY-radius*1.34f,x+radius*.62f,crownY+radius*.84f),paint);paint.setColor(mid);c.drawOval(new RectF(x-radius*.86f,crownY-radius*.55f,x+radius*.86f,crownY+radius*.55f),paint);paint.setColor(light);c.drawOval(new RectF(x-radius*.44f,crownY-radius*1.02f,x+radius*.30f,crownY-radius*.22f),paint);}
        else{paint.setColor(dark);c.drawCircle(x,crownY,radius,paint);c.drawCircle(x-radius*.56f,crownY+radius*.12f,radius*.72f,paint);c.drawCircle(x+radius*.54f,crownY+radius*.08f,radius*.70f,paint);paint.setColor(mid);c.drawCircle(x-radius*.24f,crownY-radius*.25f,radius*.66f,paint);c.drawCircle(x+radius*.37f,crownY-radius*.22f,radius*.59f,paint);paint.setColor(light);c.drawCircle(x-radius*.35f,crownY-radius*.45f,radius*.28f,paint);c.drawCircle(x+radius*.22f,crownY-radius*.48f,radius*.24f,paint);}
    }
    private void drawShrub(Canvas c,float x,float y,int t,int variant,long h){float r=t*(.23f+((h>>>47)&63)/380f);paint.setColor(Color.argb(45,4,20,12));c.drawOval(new RectF(x-r*1.4f,y-r*.15f,x+r*1.4f,y+r*.55f),paint);int dark=variant==3?Color.rgb(69,84,43):Color.rgb(42,99,50),light=variant==3?Color.rgb(111,119,56):Color.rgb(72,137,65);paint.setColor(dark);c.drawCircle(x-r*.72f,y,r*.78f,paint);c.drawCircle(x+r*.68f,y,r*.82f,paint);c.drawCircle(x,y-r*.30f,r,paint);paint.setColor(light);c.drawCircle(x-r*.25f,y-r*.46f,r*.48f,paint);if((h&3)==0){paint.setColor((h&4)==0?Color.rgb(208,72,91):Color.rgb(107,153,222));for(int i=0;i<3;i++)c.drawCircle(x+(i-1)*r*.48f,y-r*(.15f+(i&1)*.26f),Math.max(2,r*.10f),paint);}}
    private void drawFlowerPatch(Canvas c,float x,float y,int t,long h){int[] colors={Color.rgb(255,190,74),Color.rgb(208,118,226),Color.rgb(245,239,195),Color.rgb(105,181,255),Color.rgb(242,112,132)};int count=3+(int)((h>>>44)&3);for(int i=0;i<count;i++){long q=WorldMath.hash(h,i,91);float dx=((((q>>>12)&255)/255f)-.5f)*t*.72f,dy=((((q>>>22)&255)/255f)-.5f)*t*.44f;paint.setColor(Color.rgb(49,119,53));paint.setStrokeWidth(Math.max(1,t*.025f));c.drawLine(x+dx,y+dy,x+dx,y+dy+t*.20f,paint);paint.setColor(colors[(int)((q>>>34)%colors.length)]);c.drawCircle(x+dx,y+dy,Math.max(2,t*.055f),paint);paint.setColor(Color.rgb(244,210,74));c.drawCircle(x+dx,y+dy,Math.max(1,t*.020f),paint);}}
    private void drawRock(Canvas c,float x,float y,int t,int variant){float w=t*(.25f+variant*.045f),h=t*(.15f+variant*.026f);paint.setColor(Color.argb(55,5,15,18));c.drawOval(new RectF(x-w*1.1f,y,x+w*1.1f,y+h*1.7f),paint);paint.setColor(variant==3?Color.rgb(92,96,91):Color.rgb(118,121,120));c.drawOval(new RectF(x-w,y-h,x+w,y+h),paint);paint.setColor(Color.rgb(164,164,154));c.drawOval(new RectF(x-w*.62f,y-h*.82f,x+w*.20f,y-h*.16f),paint);}
    private void drawBirds(Canvas c,long now){int t=tile();paint.setStyle(Paint.Style.STROKE);paint.setStrokeWidth(Math.max(2,t*.045f));paint.setColor(Color.argb(190,28,38,48));for(int i=0;i<7;i++){long h=WorldMath.hash(seed^0xB17D,i,(int)(now/9000));float x=Math.floorMod((int)(h>>>8)+(int)(now/18)*(i%2==0?1:-1),getWidth()+240)-120,y=80+Math.floorMod((int)(h>>>24),Math.max(120,getHeight()/2));float flap=(float)Math.sin(now*.018+i);c.drawLine(x,y,x+8,y-5*flap,paint);c.drawLine(x+8,y-5*flap,x+16,y,paint);}paint.setStyle(Paint.Style.FILL);}
    private void drawResources(Canvas c){if(materials.isEmpty())return;int t=tile();float camX=playerX*t-getWidth()/2f,camY=playerY*t-getHeight()/2f;int cx=(int)Math.floor(playerX),cy=(int)Math.floor(playerY);long now=System.currentTimeMillis();harvested.entrySet().removeIf(e->now-e.getValue()>180000);for(int y=cy-10;y<=cy+10;y++)for(int x=cx-20;x<=cx+20;x++){long h=WorldMath.hash(seed^0x51AA77,x,y);if((h&15)>2)continue;long key=WorldMath.hash(seed^0x99,x,y);if(harvested.containsKey(key))continue;ContentItem m=materials.get(Math.floorMod((int)(h>>>8),materials.size()));float px=x*t-camX+t*.5f,py=y*t-camY+t*.5f;int cell=m.number("atlas_cell",-1);if(cell>=0){Rect src=new Rect((cell%4)*256,(cell/4)*256,(cell%4+1)*256,(cell/4+1)*256);c.drawBitmap(itemAtlas,src,new RectF(px-t*.34f,py-t*.34f,px+t*.34f,py+t*.34f),pixel);}else{paint.setColor(parse(m.text("color","#E0B04B"),Color.YELLOW));c.drawCircle(px,py,t*.19f,paint);}}}
    private void drawStructures(Canvas c,long now){int t=tile();float camX=playerX*t-getWidth()/2f,camY=playerY*t-getHeight()/2f;for(WorldStructure s:structures){float x=s.x*t-camX+t*.5f,y=s.y*t-camY+t*.5f;ContentItem info=structureInfo.get(s.type);float scale="small_cabin".equals(s.type)?1.45f:"timber_house".equals(s.type)?1.9f:"grand_lodge".equals(s.type)?2.45f:"wild_cave".equals(s.type)?1.55f:(info!=null&&info.number("width",1)>=4)?Math.min(2.3f,1f+info.number("width",1)*.22f):"rustic_fence".equals(s.type)?1.15f:.72f;Bitmap generated=generatedStructureSprites.get(s.type);if(generated!=null)c.drawBitmap(generated,null,new RectF(x-t*scale,y-t*scale,x+t*scale,y+t*scale),pixel);else if(isVariant(s.type)||"wild_cave".equals(s.type)){int cell="small_cabin".equals(s.type)?0:"timber_house".equals(s.type)?1:"grand_lodge".equals(s.type)?2:3;Rect src=new Rect((cell%2)*512,(cell/2)*512,(cell%2+1)*512,(cell/2+1)*512);c.drawBitmap(structureAtlas,src,new RectF(x-t*scale,y-t*scale,x+t*scale,y+t*scale),pixel);}else{int cell=structureCell(s.type);Rect src=new Rect((cell%4)*256,(cell/4)*256,(cell%4+1)*256,(cell/4+1)*256);c.drawBitmap(buildAtlas,src,new RectF(x-t*scale,y-t*scale,x+t*scale,y+t*scale),pixel);}if("campfire".equals(s.type)||"resin_torch".equals(s.type)){float flicker=(float)(.8+.2*Math.sin(now*.018+s.id));paint.setColor(Color.argb(115,255,147,34));c.drawCircle(x,y-t*.15f,t*.32f*flicker,paint);}}}
    private boolean isVariant(String type){return "small_cabin".equals(type)||"timber_house".equals(type)||"grand_lodge".equals(type);}
    private int structureCell(String type){if("campfire".equals(type))return 0;if("timber_house".equals(type))return 1;if("storage_chest".equals(type))return 3;if("bedroll".equals(type))return 7;if("resin_torch".equals(type))return 8;if("rustic_fence".equals(type))return 9;if("wooden_table".equals(type))return 11;if("cooking_pot".equals(type))return 12;return 10;}
    private void drawMobs(Canvas c,long now){int t=tile();float camX=playerX*t-getWidth()/2f,camY=playerY*t-getHeight()/2f;for(MobState mob:mobs){if(mob.health<=0)continue;float x=mob.x*t-camX+t*.5f,y=mob.y*t-camY+t*.5f,scale=mob.isBaby(now)?.52f:.82f;ContentItem info=creatureInfo.get(mob.species);int row=info==null?-1:info.number("atlas_row",-1);float gait=mob.walking?(float)Math.sin(mob.walkPhase*Math.PI):0,step=Math.abs(gait)*t*.055f,squash=1f-Math.abs(gait)*.035f;if(row>=0){int column=Math.max(0,Math.min(3,mob.facing)),cellW=mobSheet.getWidth()/4,cellH=mobSheet.getHeight()/4;Rect src=new Rect(column*cellW,row*cellH,(column+1)*cellW,(row+1)*cellH);c.drawBitmap(mobSheet,src,new RectF(x-t*scale*(2-squash),y-t*scale*squash-step,x+t*scale*(2-squash),y+t*scale*squash-step),pixel);}else{Bitmap b=generatedMobSprites.get(mob.species);if(b!=null){c.save();if(mob.facing==1){c.scale(-1,1,x,y);c.drawBitmap(b,null,new RectF(x-t*scale,y-t*scale-step,x+t*scale,y+t*scale-step),pixel);}else c.drawBitmap(b,null,new RectF(x-t*scale,y-t*scale-step,x+t*scale,y+t*scale-step),pixel);c.restore();}else{paint.setColor(info==null?Color.LTGRAY:parse(info.text("color","#BBBBBB"),Color.LTGRAY));c.drawOval(new RectF(x-t*.4f,y-t*.25f,x+t*.4f,y+t*.25f),paint);}}if(mob.loveUntil>now){paint.setColor(Color.rgb(255,88,125));paint.setTextSize(t*.48f);paint.setTextAlign(Paint.Align.CENTER);c.drawText("♥",x,y-t*.68f,paint);paint.setTextAlign(Paint.Align.LEFT);}int max=info==null?mob.health:info.number("health",mob.health);if(mob.health<max){paint.setColor(Color.argb(180,0,0,0));c.drawRect(x-t*.42f,y-t*.55f,x+t*.42f,y-t*.47f,paint);paint.setColor(Color.rgb(101,210,110));c.drawRect(x-t*.42f,y-t*.55f,x-t*.42f+t*.84f*mob.health/Math.max(1,max),y-t*.47f,paint);}}}
    private void drawInterior(Canvas c,long now){c.drawColor(Color.rgb(43,30,24));int t=Math.max(42,Math.min(64,getHeight()/9));float ox=getWidth()/2f,oy=getHeight()/2f;WorldStructure house=insideStructure;float halfW=house!=null&&"small_cabin".equals(house.type)?4.2f:house!=null&&"grand_lodge".equals(house.type)?6.3f:5.3f,halfH=house!=null&&"small_cabin".equals(house.type)?2.8f:house!=null&&"grand_lodge".equals(house.type)?4.0f:3.5f;paint.setColor(Color.rgb(134,91,49));c.drawRoundRect(ox-halfW*t,oy-halfH*t,ox+halfW*t,oy+halfH*t,t*.18f,t*.18f,paint);paint.setColor(Color.rgb(174,124,69));for(int i=(int)-halfW;i<=halfW;i++)c.drawRect(ox+i*t-t*.46f,oy-(halfH-.35f)*t,ox+i*t+t*.43f,oy+(halfH-.35f)*t,paint);paint.setColor(Color.rgb(68,43,30));paint.setStyle(Paint.Style.STROKE);paint.setStrokeWidth(t*.18f);c.drawRoundRect(ox-(halfW-.15f)*t,oy-(halfH-.15f)*t,ox+(halfW-.15f)*t,oy+(halfH-.15f)*t,t*.15f,t*.15f,paint);paint.setStyle(Paint.Style.FILL);drawBuildCell(c,2,ox,oy+(halfH-.55f)*t,t*.72f);paint.setColor(Color.argb(120,255,255,255));paint.setTextAlign(Paint.Align.CENTER);paint.setTextSize(t*.28f);c.drawText("EMPTY — PLACE YOUR OWN FURNISHINGS",ox,oy,paint);paint.setTextAlign(Paint.Align.LEFT);float px=ox+insideX*t,py=oy+insideY*t;drawPlayer(c,px,py);drawInteriorLight(c,now,ox,oy,t);}
    private void drawCaveInterior(Canvas c,long now){c.drawColor(Color.rgb(16,20,22));int t=Math.max(42,Math.min(64,getHeight()/9));float ox=getWidth()/2f,oy=getHeight()/2f;paint.setColor(Color.rgb(55,57,54));c.drawOval(new RectF(ox-5.5f*t,oy-3.7f*t,ox+5.5f*t,oy+3.7f*t),paint);paint.setColor(Color.rgb(79,75,65));for(int i=0;i<28;i++){long h=WorldMath.hash(seed^insideHouseId,i,77);float x=ox+(Math.floorMod((int)h,1000)/1000f*9.6f-4.8f)*t,y=oy+(Math.floorMod((int)(h>>>20),1000)/1000f*5.8f-2.9f)*t;c.drawCircle(x,y,t*(.08f+((h>>>40)&7)*.018f),paint);}WorldStructure cave=insideStructure;if(cave!=null&&cave.json.optBoolean("has_chest",false))drawBuildCell(c,3,ox+2.6f*t,oy-1.1f*t,t*.72f);paint.setColor(Color.rgb(30,25,22));c.drawOval(new RectF(ox-t*.8f,oy+2.55f*t,ox+t*.8f,oy+3.35f*t),paint);float px=ox+insideX*t,py=oy+insideY*t;drawPlayer(c,px,py);}
    private void drawBuildCell(Canvas c,int cell,float x,float y,float size){Rect src=new Rect((cell%4)*256,(cell/4)*256,(cell%4+1)*256,(cell/4+1)*256);c.drawBitmap(buildAtlas,src,new RectF(x-size,y-size,x+size,y+size),pixel);}
    private void drawInteriorLight(Canvas c,long now,float ox,float oy,int t){long elapsed=Math.floorMod(now-worldStart,CYCLE_MS);if(elapsed>DAY_MS){paint.setColor(Color.argb(55,18,25,62));c.drawRect(0,0,getWidth(),getHeight(),paint);paint.setColor(Color.argb(70,255,171,72));c.drawCircle(ox-2.7f*t,oy-.7f*t,t*1.8f,paint);}}
    private void drawPlayer(Canvas c,float x,float y){int t=tile();long now=System.currentTimeMillis();float phase=walking?(now%540)/540f*4f:0,gait=(float)Math.sin(phase*Math.PI/2),bob=walking?Math.abs(gait)*t*.11f:0,sway=walking?gait*t*.055f:0;float sx=(directionRow==0||directionRow==3)?sway:0,sy=(directionRow==1||directionRow==2)?sway*.35f:0;paint.setColor(Color.argb(85,0,0,0));c.drawOval(new RectF(x-t*.38f,y+t*.25f,x+t*.38f,y+t*.48f),paint);int frame=walking?(int)phase%4:0;Rect src=new Rect(frame*256,directionRow*256,(frame+1)*256,(directionRow+1)*256);RectF dst=new RectF(x-t*.72f+sx,y-t*1.15f-bob+sy,x+t*.72f+sx,y+t*.58f-bob+sy);paint.setColor(Color.WHITE);paint.setAlpha(255);c.drawBitmap(playerSheet,src,dst,paint);}
    private void drawAtmosphere(Canvas c,long now){long elapsed=Math.floorMod(now-worldStart,CYCLE_MS);float light=dayLight(elapsed);int dark=(int)((1-light)*175);if(dark>0){paint.setColor(Color.argb(dark,8,16,48));c.drawRect(0,0,getWidth(),getHeight(),paint);}ContentItem w=currentWeather(now);String effect=w==null?"clear":w.text("effect",weatherEffect(w.identity));long segment=(now-worldStart)/WEATHER_MS;if("rain".equals(effect)||"storm".equals(effect)){paint.setColor(Color.argb("storm".equals(effect)?150:105,160,205,230));paint.setStrokeWidth(2);int count="storm".equals(effect)?95:60;for(int i=0;i<count;i++){long h=WorldMath.hash(seed^segment,i,17);float x=Math.floorMod((int)h,getWidth()+80)-40,y=Math.floorMod((int)(h>>>20)+(int)(now/9),getHeight()+100)-50;c.drawLine(x,y,x-12,y+24,paint);}if("storm".equals(effect)&&now%11000<110){paint.setColor(Color.argb(100,220,235,255));c.drawRect(0,0,getWidth(),getHeight(),paint);}}else if("snow".equals(effect)){paint.setColor(Color.argb(180,245,252,255));for(int i=0;i<55;i++){long h=WorldMath.hash(seed^segment,i,41);float x=Math.floorMod((int)h+(int)(now/28),getWidth()),y=Math.floorMod((int)(h>>>18)+(int)(now/16),getHeight());c.drawCircle(x,y,2+(i%3),paint);}}else if("fog".equals(effect)){paint.setColor(Color.argb(42,215,225,220));for(int i=0;i<6;i++){float y=(i+.5f)*getHeight()/6f+(float)Math.sin(now*.0003+i)*35;c.drawRoundRect(-40,y-34,getWidth()+40,y+34,40,40,paint);}}for(WorldStructure s:structures)if("campfire".equals(s.type)||"resin_torch".equals(s.type)){int t=tile();float camX=playerX*t-getWidth()/2f,camY=playerY*t-getHeight()/2f,x=s.x*t-camX+t*.5f,y=s.y*t-camY+t*.5f;paint.setColor(Color.argb(65,255,156,54));c.drawCircle(x,y,"campfire".equals(s.type)?t*2.1f:t*1.3f,paint);}}
    private float dayLight(long elapsed){if(elapsed<DAY_MS){if(elapsed<90000)return .55f+.45f*elapsed/90000f;if(elapsed>DAY_MS-120000)return .45f+.55f*(DAY_MS-elapsed)/120000f;return 1f;}long night=elapsed-DAY_MS;if(night<90000)return .18f+.27f*(90000-night)/90000f;if(night>NIGHT_MS-90000)return .18f+.37f*(night-(NIGHT_MS-90000))/90000f;return .18f;}
    private ContentItem currentWeather(long now){if(weather.isEmpty())return null;long segment=(now-worldStart)/WEATHER_MS;long h=WorldMath.hash(seed^0x7711,(int)segment,29);return weather.get(Math.floorMod((int)h,weather.size()));}
    private String weatherEffect(String identity){if(identity.contains("rain"))return "rain";if(identity.contains("storm"))return "storm";if(identity.contains("snow"))return "snow";if(identity.contains("fog"))return "fog";return "clear";}
    private void drawHud(Canvas c,long now){paint.setTextSize(16*getResources().getDisplayMetrics().scaledDensity);paint.setColor(Color.argb(205,4,18,35));c.drawRoundRect(14,12,inside?430:500,88,16,16,paint);paint.setColor(Color.WHITE);String place=inside?(insideCave?"INSIDE WILD CAVE":"INSIDE "+structureName(insideStructure)):"INFINITE RPG  •  "+Math.round(playerX)+", "+Math.round(playerY);c.drawText(place,28,38,paint);paint.setTextSize(12*getResources().getDisplayMetrics().scaledDensity);paint.setColor(Color.rgb(116,205,143));ContentItem w=currentWeather(now);c.drawText("HP "+health+"   ENERGY "+energy+"   "+clockText(now)+"   "+(w==null?"Clear":w.name),28,66,paint);if(!placing)drawControls(c,now);if(now<toastUntil){paint.setColor(Color.argb(220,5,25,42));c.drawRoundRect(getWidth()/2f-235,getHeight()-58,getWidth()/2f+235,getHeight()-16,15,15,paint);paint.setColor(Color.WHITE);paint.setTextAlign(Paint.Align.CENTER);c.drawText(toast,getWidth()/2f,getHeight()-32,paint);paint.setTextAlign(Paint.Align.LEFT);}}
    private String clockText(long now){long elapsed=Math.floorMod(now-worldStart,CYCLE_MS);boolean day=elapsed<DAY_MS;if(!hasClock)return day?"DAY":"NIGHT";long part=day?elapsed:elapsed-DAY_MS,total=day?DAY_MS:NIGHT_MS;int hour=day?6+(int)(part*12/total):18+(int)(part*12/total);hour%=24;int minute=(int)((part*12*60/total)%60);return (day?"DAY ":"NIGHT ")+String.format(Locale.US,"%02d:%02d",hour,minute);}
    private void drawControls(Canvas c,long now){float gx=getWidth()-105,gy=getHeight()-95,ax=getWidth()-225,ay=getHeight()-95,ux=getWidth()-105,uy=getHeight()-210;buttonCircle(c,gx,gy,50,"GATHER",UiColors.GOLD);buttonCircle(c,ax,ay,50,"ATTACK",Color.rgb(224,96,78));buttonCircle(c,ux,uy,50,useLabel(now),Color.rgb(80,196,220));float jx=105,jy=getHeight()-105;paint.setColor(Color.argb(130,5,25,42));c.drawCircle(jx,jy,66,paint);paint.setColor(Color.argb(205,72,202,228));c.drawCircle(jx+joyX*40,jy+joyY*40,25,paint);}
    private void buttonCircle(Canvas c,float x,float y,float r,String label,int color){paint.setColor(Color.argb(205,5,25,42));c.drawCircle(x,y,r,paint);paint.setColor(color);paint.setTextSize(12*getResources().getDisplayMetrics().scaledDensity);paint.setTextAlign(Paint.Align.CENTER);c.drawText(label,x,y+5,paint);paint.setTextAlign(Paint.Align.LEFT);}
    public void beginPlacement(String itemKey,String structureType,ContentItem blueprint){if(inside){say("Leave the interior before building");return;}placing=true;placeItemKey=itemKey;placeType=structureType;placeBlueprint=blueprint;float dx=directionRow==1?-3:directionRow==2?3:0,dy=directionRow==3?-3:directionRow==0?3:0;placeX=playerX+dx;placeY=playerY+dy;joyX=joyY=0;say("Tap the exact spot, then press CONFIRM");invalidate();}
    private void drawPlacement(Canvas c){int t=tile();float x=getWidth()/2f+(placeX-playerX)*t+t*.5f,y=getHeight()/2f+(placeY-playerY)*t+t*.5f;paint.setColor(Color.argb(120,60,220,160));c.drawCircle(x,y,t*.75f,paint);pixel.setAlpha(155);if(isVariant(placeType)){int cell="small_cabin".equals(placeType)?0:"timber_house".equals(placeType)?1:2;Rect src=new Rect((cell%2)*512,(cell/2)*512,(cell%2+1)*512,(cell/2+1)*512);float scale="small_cabin".equals(placeType)?1.45f:"grand_lodge".equals(placeType)?2.45f:1.9f;c.drawBitmap(structureAtlas,src,new RectF(x-t*scale,y-t*scale,x+t*scale,y+t*scale),pixel);}else if(placeBlueprint!=null&&generatedStructureSprites.get(placeType)!=null){float s=t*1.2f;c.drawBitmap(generatedStructureSprites.get(placeType),null,new RectF(x-s,y-s,x+s,y+s),pixel);}else{int cell=structureCell(placeType);Rect src=new Rect((cell%4)*256,(cell/4)*256,(cell%4+1)*256,(cell/4+1)*256);c.drawBitmap(buildAtlas,src,new RectF(x-t*.85f,y-t*.85f,x+t*.85f,y+t*.85f),pixel);}pixel.setAlpha(255);float by=getHeight()-76,bx=getWidth()/2f;paint.setColor(Color.argb(230,23,104,75));c.drawRoundRect(bx-170,by-28,bx-15,by+28,14,14,paint);paint.setColor(Color.argb(230,145,58,56));c.drawRoundRect(bx+15,by-28,bx+170,by+28,14,14,paint);paint.setTextSize(14*getResources().getDisplayMetrics().scaledDensity);paint.setTextAlign(Paint.Align.CENTER);paint.setColor(Color.WHITE);c.drawText("CONFIRM",bx-92,by+6,paint);c.drawText("CANCEL",bx+92,by+6,paint);paint.setTextAlign(Paint.Align.LEFT);}
    private void confirmPlacement(){long id=placeBlueprint==null?repo.placeStructureAt(placeType,placeItemKey,placeX,placeY):repo.buildGeneratedStructureAt(placeBlueprint,placeX,placeY);if(id>0){placing=false;say("Built "+placeType.replace('_',' ')+" at the chosen spot");refreshWorld();}else say(id==-2?"That spot is blocked":id==-3?"Choose a spot closer to your character":"Missing required materials");}
    private String useLabel(long now){if(inside){WorldStructure room=insideStructure;if(insideCave&&room!=null&&room.json.optBoolean("has_chest",false)&&Math.hypot(insideX-2.6,insideY+1.1)<2)return "CHEST";if(Math.hypot(insideX,insideY-(insideLimitY-.2f))<2)return "EXIT";return "USE";}WorldStructure s=nearestStructure(2.8);if(s!=null){ContentItem info=structureInfo.get(s.type);if("wild_cave".equals(s.type)||isVariant(s.type)||(info!=null&&info.json.optBoolean("enterable",false)))return "ENTER";if("storage_chest".equals(s.type)||(info!=null&&info.number("storage_slots",0)>0))return "OPEN";if("campfire".equals(s.type))return "COOK";}MobState mob=nearestMob(2.5);return mob==null?"USE":"FEED";}
    @Override public boolean onTouchEvent(MotionEvent e){RuntimeSignals.gameBusy();int action=e.getActionMasked(),index=e.getActionIndex();if(placing){if(action==MotionEvent.ACTION_DOWN){float x=e.getX(index),y=e.getY(index),bx=getWidth()/2f,by=getHeight()-76;if(y>by-45&&y<by+45&&x>bx-190&&x<bx-5){confirmPlacement();return true;}if(y>by-45&&y<by+45&&x>bx+5&&x<bx+190){placing=false;say("Placement cancelled");return true;}int t=tile();placeX=playerX+(x-getWidth()/2f-t*.5f)/t;placeY=playerY+(y-getHeight()/2f-t*.5f)/t;say("Spot selected — press CONFIRM");}return true;}float gx=getWidth()-105,gy=getHeight()-95,ax=getWidth()-225,ay=getHeight()-95,ux=getWidth()-105,uy=getHeight()-210;int id=e.getPointerId(index);if(action==MotionEvent.ACTION_DOWN||action==MotionEvent.ACTION_POINTER_DOWN){float x=e.getX(index),y=e.getY(index);if(Math.hypot(x-gx,y-gy)<65){gather();return true;}if(Math.hypot(x-ax,y-ay)<65){attack();return true;}if(Math.hypot(x-ux,y-uy)<65){use();return true;}if(x<getWidth()*.45f&&y>getHeight()*.40f&&joyPointer<0)joyPointer=id;}if(action==MotionEvent.ACTION_UP||action==MotionEvent.ACTION_POINTER_UP||action==MotionEvent.ACTION_CANCEL){if(id==joyPointer){joyPointer=-1;joyX=joyY=0;}}if(joyPointer>=0){int pi=e.findPointerIndex(joyPointer);if(pi>=0){float dx=e.getX(pi)-105,dy=e.getY(pi)-(getHeight()-105);float len=(float)Math.hypot(dx,dy);if(len>60){dx*=60/len;dy*=60/len;}joyX=dx/60;joyY=dy/60;}}return true;}
    private void gather(){if(inside){say("There are no wild resources inside");return;}if(materials.isEmpty())return;int cx=Math.round(playerX),cy=Math.round(playerY);double best=2;long bestKey=0,bestHash=0;for(int y=cy-2;y<=cy+2;y++)for(int x=cx-2;x<=cx+2;x++){long h=WorldMath.hash(seed^0x51AA77,x,y);if((h&15)>2)continue;long key=WorldMath.hash(seed^0x99,x,y);if(harvested.containsKey(key))continue;double d=Math.hypot(playerX-x,playerY-y);if(d<best){best=d;bestKey=key;bestHash=h;}}if(bestKey==0){say("Nothing gatherable nearby");return;}ContentItem m=materials.get(Math.floorMod((int)(bestHash>>>8),materials.size()));int qty=m.number("gather_min",1)+Math.floorMod((int)(bestHash>>>16),Math.max(1,m.number("gather_max",3)-m.number("gather_min",1)+1));repo.addInventory(m.identity,qty);harvested.put(bestKey,System.currentTimeMillis());say("Gathered "+qty+" × "+m.name);}
    private void attack(){if(inside){say("No fighting inside your home");return;}MobState mob=nearestMob(2.7);if(mob==null){say("No animal in attack range");return;}int left=repo.damageMob(mob.id,7);mob.health=left;if(left>0){say("Hit "+mobName(mob)+" — "+left+" health left");return;}ContentItem info=creatureInfo.get(mob.species);JSONObject drops=info==null?null:info.json.optJSONObject("drops");StringBuilder found=new StringBuilder();if(drops!=null){JSONArray keys=drops.names();if(keys!=null)for(int i=0;i<keys.length();i++){String key=keys.optString(i);int qty=drops.optInt(key,1);repo.addInventory(key,qty);if(found.length()>0)found.append(", ");found.append(qty).append(' ').append(key.replace('_',' '));}}mobs.remove(mob);say("Hunted "+mobName(mob)+(found.length()>0?" • gained "+found:""));}
    private void use(){long now=System.currentTimeMillis();if(inside){WorldStructure room=insideStructure;if(insideCave&&room!=null&&room.json.optBoolean("has_chest",false)&&Math.hypot(insideX-2.6,insideY+1.1)<2){listener.openChest(insideHouseId);return;}if(Math.hypot(insideX,insideY-(insideLimitY-.2f))<2){inside=false;insideCave=false;if(room!=null){playerX=room.x;playerY=room.y+2.5f;}insideHouseId=-1;insideStructure=null;say("Returned to the world");refreshWorld();return;}say(insideCave?"Move near the cave chest or exit":"This new house is empty — move to the door to exit");return;}WorldStructure s=nearestStructure(2.8);if(s!=null){ContentItem info=structureInfo.get(s.type);boolean cave="wild_cave".equals(s.type),enterable=cave||isVariant(s.type)||(info!=null&&info.json.optBoolean("enterable",false)),storage="storage_chest".equals(s.type)||(info!=null&&info.number("storage_slots",0)>0);if(enterable){inside=true;insideCave=cave;insideHouseId=s.id;insideStructure=s;insideX=0;if(cave){insideLimitX=4.4f;insideLimitY=2.7f;}else if("small_cabin".equals(s.type)){insideLimitX=3.5f;insideLimitY=2.1f;}else if("grand_lodge".equals(s.type)){insideLimitX=5.7f;insideLimitY=3.4f;}else{insideLimitX=4.6f;insideLimitY=2.9f;}insideY=insideLimitY-.5f;say("Entered "+structureName(s));return;}if(storage){listener.openChest(s.id);return;}if("campfire".equals(s.type)){if(repo.consumeInventory("raw_meat",1)){repo.addInventory("cooked_meat",1);say("Cooked raw meat over the campfire");}else say("Bring raw meat here to cook");return;}}MobState mob=nearestMob(2.5);if(mob!=null){feed(mob,now);return;}say("Nothing nearby to use");}
    private void feed(MobState mob,long now){ContentItem info=creatureInfo.get(mob.species);if(info==null){say("This creature cannot be bred yet");return;}if(mob.isBaby(now)){say("This "+mobName(mob)+" is still a baby");return;}if(mob.cooldownUntil>now){say("This "+mobName(mob)+" needs more time before breeding again");return;}String food=info.text("food","animal_feed");if(!repo.consumeInventory(food,1)){say("Need 1 "+food.replace('_',' ') +" to feed it");return;}mob.loveUntil=now+60000;repo.updateMob(mob);MobState mate=null;for(MobState other:mobs)if(other.id!=mob.id&&other.species.equals(mob.species)&&!other.isBaby(now)&&other.loveUntil>now&&other.cooldownUntil<=now&&Math.hypot(other.x-mob.x,other.y-mob.y)<3.5){mate=other;break;}if(mate==null){say("♥ "+mobName(mob)+" is ready — feed a nearby mate");return;}mob.loveUntil=mate.loveUntil=0;mob.cooldownUntil=mate.cooldownUntil=now+5*60*1000L;repo.updateMob(mob);repo.updateMob(mate);int max=info.number("health",12);MobState baby=repo.spawnBaby(mob.species,(mob.x+mate.x)/2,(mob.y+mate.y)/2,max,mob.id,mate.id);mobs.add(baby);say("♥ A baby "+mobName(baby)+" was born");}
    private WorldStructure nearestStructure(double radius){WorldStructure best=null;double distance=radius;for(WorldStructure s:structures){double d=Math.hypot(playerX-s.x,playerY-s.y);if(d<distance){distance=d;best=s;}}return best;}
    private MobState nearestMob(double radius){MobState best=null;double distance=radius;for(MobState m:mobs){double d=Math.hypot(playerX-m.x,playerY-m.y);if(m.health>0&&d<distance){distance=d;best=m;}}return best;}
    private String mobName(MobState mob){ContentItem i=creatureInfo.get(mob.species);return i==null?mob.species.replace('_',' '):i.name;}
    private String structureName(WorldStructure structure){if(structure==null)return "structure";ContentItem i=structureInfo.get(structure.type);return i==null?structure.type.replace('_',' '):i.name;}
    private int parse(String s,int fallback){try{return Color.parseColor(s);}catch(Exception e){return fallback;}}
    private long number(String value,long fallback){try{return Long.parseLong(value);}catch(Exception e){return fallback;}}
    private void say(String value){toast=value;toastUntil=System.currentTimeMillis()+3500;invalidate();}
    @Override protected void onAttachedToWindow(){super.onAttachedToWindow();lastFrame=System.nanoTime();RuntimeSignals.setGameplayActive(true);}
    @Override protected void onDetachedFromWindow(){RuntimeSignals.setGameplayActive(false);super.onDetachedFromWindow();}
    public void save(){repo.savePlayer(playerX,playerY,health,energy);}
    private static final class UiColors {static final int GOLD=Color.rgb(255,200,87);}
}
