package app.infiniterpg.ui;

import android.content.Context;
import android.graphics.Color;
import android.view.Gravity;
import android.widget.Button;
import android.widget.GridLayout;
import android.widget.LinearLayout;
import android.widget.ScrollView;
import android.widget.TextView;
import android.widget.Toast;
import org.json.JSONArray;
import org.json.JSONObject;
import app.infiniterpg.data.ContentItem;
import app.infiniterpg.data.ContentRepository;
import java.util.List;

/** The bag is the real inventory, crafting book, and build-placement screen. */
public final class CraftingView extends LinearLayout {
    public interface BuildListener{void place(String itemKey,String structureType,ContentItem blueprint);}
    private final ContentRepository repo;private final Runnable onBack;private final BuildListener buildListener;private final LinearLayout page;private int tab;
    public CraftingView(Context context,ContentRepository repo,Runnable onBack,BuildListener buildListener,int initialTab){super(context);this.repo=repo;this.onBack=onBack;this.buildListener=buildListener;setOrientation(VERTICAL);setBackgroundColor(Ui.BG);setPadding(Ui.dp(context,22),Ui.dp(context,10),Ui.dp(context,22),Ui.dp(context,10));
        LinearLayout head=new LinearLayout(context);head.setGravity(Gravity.CENTER_VERTICAL);TextView title=Ui.text(context,"🎒  BACKPACK",24,Ui.GOLD);title.setTypeface(null,1);head.addView(title,new LayoutParams(0,Ui.dp(context,50),1));Button back=Ui.button(context,"← Back to world");back.setOnClickListener(v->onBack.run());head.addView(back,new LayoutParams(Ui.dp(context,170),Ui.dp(context,44)));addView(head);
        LinearLayout tabs=new LinearLayout(context);addTab(tabs,"INVENTORY",0);addTab(tabs,"CRAFTING",1);addTab(tabs,"BUILD",2);addView(tabs,new LayoutParams(-1,Ui.dp(context,46)));page=new LinearLayout(context);page.setOrientation(VERTICAL);ScrollView scroll=new ScrollView(context);scroll.addView(page);addView(scroll,new LayoutParams(-1,0,1));showTab(initialTab);}
    private void addTab(LinearLayout row,String label,int value){Button b=Ui.button(getContext(),label);b.setOnClickListener(v->showTab(value));LayoutParams lp=new LayoutParams(0,Ui.dp(getContext(),42),1);lp.setMargins(0,0,Ui.dp(getContext(),8),0);row.addView(b,lp);}
    private void showTab(int value){tab=value;page.removeAllViews();if(tab==0)showInventory();else if(tab==1)showRecipes();else showBuildables();}
    private void showInventory(){page.addView(heading("EVERY ITEM YOU CARRY"));List<String[]> inv=repo.inventoryList();if(inv.isEmpty()){page.addView(Ui.text(getContext(),"Your backpack is empty. Gather resources, hunt animals, or take items from a chest.",15,Ui.MUTED));return;}GridLayout grid=new GridLayout(getContext());grid.setColumnCount(7);for(String[] row:inv)addInventoryTile(grid,row[0],Integer.parseInt(row[1]));page.addView(grid,new LayoutParams(-1,-2));}
    private void addInventoryTile(GridLayout grid,String key,int quantity){ContentItem item=resolve(key);LinearLayout tile=new LinearLayout(getContext());tile.setOrientation(VERTICAL);tile.setGravity(Gravity.CENTER);tile.setPadding(Ui.dp(getContext(),5),Ui.dp(getContext(),5),Ui.dp(getContext(),5),Ui.dp(getContext(),4));tile.setBackground(Ui.round(Ui.PANEL,12,Color.rgb(34,77,95),1));tile.addView(new ItemIconView(getContext(),item),new LayoutParams(Ui.dp(getContext(),68),Ui.dp(getContext(),68)));String name=item==null?key.replace('_',' '):item.name;TextView label=Ui.text(getContext(),quantity+"×  "+name,11,Ui.TEXT);label.setGravity(Gravity.CENTER);tile.addView(label,new LayoutParams(Ui.dp(getContext(),112),Ui.dp(getContext(),34)));GridLayout.LayoutParams gp=new GridLayout.LayoutParams();gp.width=Ui.dp(getContext(),120);gp.height=Ui.dp(getContext(),112);gp.setMargins(Ui.dp(getContext(),4),Ui.dp(getContext(),4),Ui.dp(getContext(),4),Ui.dp(getContext(),4));grid.addView(tile,gp);}
    private void showRecipes(){page.addView(heading("CRAFTING BOOK — TAP CRAFT TO MAKE THE ITEM"));for(ContentItem recipe:repo.list("RECIPE",300))addRecipe(recipe);}
    private void addRecipe(ContentItem recipe){LinearLayout card=card();String resultKey=recipe.json.optString("result",recipe.identity);ContentItem result=resolve(resultKey);card.addView(new ItemIconView(getContext(),result),new LayoutParams(Ui.dp(getContext(),70),Ui.dp(getContext(),70)));TextView copy=Ui.text(getContext(),recipe.name+"\n"+ingredients(recipe.json.optJSONObject("ingredients")),14,Ui.TEXT);LayoutParams cp=new LayoutParams(0,Ui.dp(getContext(),72),1);cp.setMargins(Ui.dp(getContext(),10),0,0,0);card.addView(copy,cp);Button make=Ui.button(getContext(),"Craft");make.setOnClickListener(v->{boolean ok=repo.craft(recipe);Toast.makeText(getContext(),ok?"Crafted "+recipe.name:"Missing ingredients",Toast.LENGTH_SHORT).show();showTab(1);});card.addView(make,new LayoutParams(Ui.dp(getContext(),112),Ui.dp(getContext(),48)));page.addView(card,rowParams(84));}
    private void showBuildables(){page.addView(heading("CHOOSE A BUILD, THEN TAP ITS EXACT SPOT IN THE WORLD"));addBuild("campfire_kit","campfire","Campfire","Warm light, cooking, and a safe-looking campsite.");addBuild("small_cabin_kit","small_cabin","Small Cabin","A compact empty cabin with a working door.");addBuild("timber_house_kit","timber_house","Timber Cottage","A medium empty cottage with a working door.");addBuild("grand_lodge_kit","grand_lodge","Grand Lodge","A large empty lodge with working double doors.");addBuild("storage_chest_kit","storage_chest","Storage Chest","Persistent two-way storage that opens when used.");addBuild("bedroll","bedroll","Bedroll","A warm camp furnishing.");addBuild("resin_torch","resin_torch","Torch","A permanent warm light source.");addBuild("rustic_fence","rustic_fence","Fence","A rustic boundary section.");addBuild("wooden_table","wooden_table","Table","Furniture for camp or home.");addBuild("cooking_pot","cooking_pot","Cooking Pot","A pot to place beside a campfire.");for(ContentItem blueprint:repo.list("STRUCTURE",100))if(!blueprint.identity.equals("campfire")&&!blueprint.identity.equals("small_cabin")&&!blueprint.identity.equals("timber_house")&&!blueprint.identity.equals("grand_lodge")&&!blueprint.identity.equals("storage_chest")&&!blueprint.identity.equals("wild_cave"))addGeneratedBuild(blueprint);}
    private void addBuild(String itemKey,String structureType,String title,String description){ContentItem item=resolve(itemKey);int owned=repo.inventory(itemKey);LinearLayout card=card();card.addView(new ItemIconView(getContext(),item),new LayoutParams(Ui.dp(getContext(),70),Ui.dp(getContext(),70)));TextView copy=Ui.text(getContext(),title+"  •  owned "+owned+"\n"+description,14,owned>0?Ui.TEXT:Ui.MUTED);LayoutParams cp=new LayoutParams(0,Ui.dp(getContext(),72),1);cp.setMargins(Ui.dp(getContext(),10),0,0,0);card.addView(copy,cp);Button place=Ui.button(getContext(),"Choose spot");place.setEnabled(owned>0);place.setOnClickListener(v->buildListener.place(itemKey,structureType,null));card.addView(place,new LayoutParams(Ui.dp(getContext(),132),Ui.dp(getContext(),48)));page.addView(card,rowParams(84));}
    private void addGeneratedBuild(ContentItem blueprint){JSONObject required=blueprint.json.optJSONObject("required_items");boolean ready=hasIngredients(required);LinearLayout card=card();card.addView(new ItemIconView(getContext(),blueprint),new LayoutParams(Ui.dp(getContext(),70),Ui.dp(getContext(),70)));TextView copy=Ui.text(getContext(),"AI BLUEPRINT • "+blueprint.name+"\n"+ingredients(required),14,ready?Ui.TEXT:Ui.MUTED);LayoutParams cp=new LayoutParams(0,Ui.dp(getContext(),72),1);cp.setMargins(Ui.dp(getContext(),10),0,0,0);card.addView(copy,cp);Button build=Ui.button(getContext(),"Choose spot");build.setEnabled(ready);build.setOnClickListener(v->buildListener.place(null,blueprint.identity,blueprint));card.addView(build,new LayoutParams(Ui.dp(getContext(),132),Ui.dp(getContext(),48)));page.addView(card,rowParams(84));}
    private boolean hasIngredients(JSONObject ingredients){if(ingredients==null)return false;JSONArray names=ingredients.names();if(names==null)return false;for(int i=0;i<names.length();i++){String key=names.optString(i);if(repo.inventory(key)<ingredients.optInt(key))return false;}return true;}
    private ContentItem resolve(String key){ContentItem item=repo.byIdentity("ITEM",key);if(item==null)item=repo.byIdentity("MATERIAL",key);if(item==null)item=repo.byIdentity("STRUCTURE",key);return item;}
    private String ingredients(JSONObject o){if(o==null)return "No ingredients";JSONArray names=o.names();StringBuilder s=new StringBuilder();if(names!=null)for(int i=0;i<names.length();i++){String k=names.optString(i);if(i>0)s.append("   •   ");int need=o.optInt(k),have=repo.inventory(k);s.append(have).append('/').append(need).append(' ').append(k.replace('_',' '));}return s.toString();}
    private TextView heading(String value){TextView t=Ui.text(getContext(),value,16,Ui.CYAN);t.setTypeface(null,1);t.setPadding(0,Ui.dp(getContext(),8),0,Ui.dp(getContext(),8));return t;}
    private LinearLayout card(){LinearLayout card=new LinearLayout(getContext());card.setGravity(Gravity.CENTER_VERTICAL);card.setPadding(Ui.dp(getContext(),8),Ui.dp(getContext(),6),Ui.dp(getContext(),12),Ui.dp(getContext(),6));card.setBackground(Ui.round(Ui.PANEL,14,Color.rgb(34,77,95),1));return card;}
    private LayoutParams rowParams(int height){LayoutParams lp=new LayoutParams(-1,Ui.dp(getContext(),height));lp.setMargins(0,0,0,Ui.dp(getContext(),7));return lp;}
}
