package app.infiniterpg.ui;

import android.app.ActivityManager;
import android.content.Context;
import android.content.Intent;
import android.content.res.ColorStateList;
import android.graphics.Typeface;
import android.os.Build;
import android.os.Handler;
import android.os.Looper;
import android.os.PowerManager;
import android.view.Gravity;
import android.widget.Button;
import android.widget.ArrayAdapter;
import android.widget.EditText;
import android.widget.LinearLayout;
import android.widget.ProgressBar;
import android.widget.ScrollView;
import android.widget.SeekBar;
import android.widget.Spinner;
import android.widget.TextView;
import android.widget.Toast;
import org.json.JSONObject;
import app.infiniterpg.ai.ModelBank;
import app.infiniterpg.ai.ModelCatalog;
import app.infiniterpg.ai.WorldGeneratorService;
import app.infiniterpg.data.ContentItem;
import app.infiniterpg.data.ContentRepository;
import app.infiniterpg.data.WorldSaveManager;
import java.util.LinkedHashMap;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;

/** Tabbed control center. Fast values are updated in place instead of rebuilding the entire view. */
public final class SettingsView extends LinearLayout {
    private final ContentRepository repo;private final Runnable onBack,onWorldChanged,onImportModel;private final WorldSaveManager worldSaves;private final Handler handler=new Handler(Looper.getMainLooper());private final LinearLayout page;
    private final Map<String,TextView> statusValues=new LinkedHashMap<>();private int selectedTab;
    private ProgressBar downloadProgress;private TextView downloadLabel,streamHeader,streamStatus,promptText,outputText,musicNow,musicToggle,volumeLabel;private ScrollView streamOutputScroll;private LinearLayout creationList,eventList;
    private long lastStatsAt,lastListsAt,lastCreationSeq=Long.MIN_VALUE;private int musicTrackCount;

    public SettingsView(Context context,ContentRepository repo,Runnable onBack,Runnable onWorldChanged,Runnable onImportModel){
        super(context);this.repo=repo;this.onBack=onBack;this.onWorldChanged=onWorldChanged;this.onImportModel=onImportModel;worldSaves=new WorldSaveManager(context,repo);setOrientation(VERTICAL);setBackgroundColor(Ui.BG);setPadding(Ui.dp(context,22),Ui.dp(context,10),Ui.dp(context,22),Ui.dp(context,10));
        LinearLayout head=new LinearLayout(context);head.setGravity(Gravity.CENTER_VERTICAL);TextView title=Ui.text(context,"INFINITE RPG MENU",23,Ui.GOLD);title.setTypeface(Typeface.DEFAULT,Typeface.BOLD);head.addView(title,new LayoutParams(0,Ui.dp(context,48),1));Button back=Ui.button(context,"← Back to world");back.setOnClickListener(v->onBack.run());head.addView(back,new LayoutParams(Ui.dp(context,170),Ui.dp(context,44)));addView(head);
        LinearLayout tabs=new LinearLayout(context);tabs.setGravity(Gravity.CENTER_VERTICAL);addTab(tabs,"✦ AI FORGE",0);addTab(tabs,"▰ AI STREAM",1);addTab(tabs,"♫ AUDIO",2);addTab(tabs,"◈ WORLD",3);addTab(tabs,"⚙ SETTINGS",4);addView(tabs,new LayoutParams(-1,Ui.dp(context,48)));
        page=new LinearLayout(context);page.setOrientation(VERTICAL);addView(page,new LayoutParams(-1,0,1));showTab(0);
    }

    private void addTab(LinearLayout row,String label,int index){Button b=Ui.button(getContext(),label);b.setOnClickListener(v->showTab(index));LayoutParams lp=new LayoutParams(0,Ui.dp(getContext(),43),1);lp.setMargins(0,0,Ui.dp(getContext(),8),0);row.addView(b,lp);}
    private void showTab(int tab){selectedTab=tab;page.removeAllViews();statusValues.clear();downloadProgress=null;downloadLabel=null;streamHeader=null;streamStatus=null;promptText=null;outputText=null;streamOutputScroll=null;musicNow=null;musicToggle=null;volumeLabel=null;creationList=null;eventList=null;if(tab==0)buildAi();else if(tab==1)buildStream();else if(tab==2)buildAudio();else if(tab==3)buildWorld();else buildSettings();}

    private void buildAi(){
        ModelBank bank=new ModelBank(getContext());List<ModelBank.ModelInfo> banked=bank.list();ArrayList<String> labels=new ArrayList<>(),keys=new ArrayList<>();for(ModelCatalog.Profile p:ModelCatalog.PRESETS){labels.add(p.label+" — "+p.note);keys.add(p.key);}for(ModelBank.ModelInfo info:banked){String key="bank:"+info.name;if(ModelCatalog.byKey(repo.getState("selected_model_key",""))!=null&&info.name.equalsIgnoreCase(ModelCatalog.selected(repo).fileName))continue;labels.add("BANK: "+info.name+" • "+(info.bytes/1048576)+" MiB");keys.add(key);}Spinner chooser=new Spinner(getContext());ArrayAdapter<String> adapter=new ArrayAdapter<>(getContext(),android.R.layout.simple_spinner_item,labels);adapter.setDropDownViewResource(android.R.layout.simple_spinner_dropdown_item);chooser.setAdapter(adapter);String current=repo.getState("selected_model_key","qwen25_q8");int currentIndex=keys.indexOf(current);if(currentIndex>=0)chooser.setSelection(currentIndex);LinearLayout modelRow=new LinearLayout(getContext());modelRow.setGravity(Gravity.CENTER_VERTICAL);modelRow.addView(chooser,new LayoutParams(0,Ui.dp(getContext(),44),1));Button use=Ui.button(getContext(),"Use model");use.setOnClickListener(v->{String key=keys.get(chooser.getSelectedItemPosition());ModelCatalog.Profile preset=ModelCatalog.byKey(key);if(preset!=null)ModelCatalog.select(repo,preset);else{ModelBank.ModelInfo info=bank.find(key.substring(5));if(info!=null)ModelCatalog.selectBank(repo,info.name,info.bytes);}getContext().startForegroundService(new Intent(getContext(),WorldGeneratorService.class).setAction(WorldGeneratorService.ACTION_RELOAD_MODEL));Toast.makeText(getContext(),"Switching to "+ModelCatalog.selected(repo).label,Toast.LENGTH_LONG).show();handler.postDelayed(()->showTab(0),350);});modelRow.addView(use,new LayoutParams(Ui.dp(getContext(),118),Ui.dp(getContext(),42)));Button importModel=Ui.button(getContext(),"Import GGUF");importModel.setOnClickListener(v->onImportModel.run());modelRow.addView(importModel,new LayoutParams(Ui.dp(getContext(),130),Ui.dp(getContext(),42)));page.addView(modelRow,new LayoutParams(-1,Ui.dp(getContext(),46)));
        ModelCatalog.Profile selected=ModelCatalog.selected(repo);LinearLayout settingRow=new LinearLayout(getContext());settingRow.setGravity(Gravity.CENTER_VERTICAL);EditText ctx=numberField("Context",repo.getState("model_context",Integer.toString(selected.context)));EditText max=numberField("Output",repo.getState("model_max_tokens",Integer.toString(selected.maxTokens)));EditText threads=numberField("Threads",repo.getState("model_threads",Integer.toString(selected.threads)));EditText temp=numberField("Temp",repo.getState("model_temperature",Float.toString(selected.temperature)));Spinner template=new Spinner(getContext());String[] templateLabels={"ChatML template","Llama 3 template","Plain prompt"};ArrayAdapter<String> ta=new ArrayAdapter<>(getContext(),android.R.layout.simple_spinner_item,templateLabels);ta.setDropDownViewResource(android.R.layout.simple_spinner_dropdown_item);template.setAdapter(ta);String selectedTemplate=repo.getState("model_template",selected.template);template.setSelection("llama3".equals(selectedTemplate)?1:"plain".equals(selectedTemplate)?2:0);settingRow.addView(ctx,new LayoutParams(0,Ui.dp(getContext(),44),.75f));settingRow.addView(max,new LayoutParams(0,Ui.dp(getContext(),44),.75f));settingRow.addView(threads,new LayoutParams(0,Ui.dp(getContext(),44),.65f));settingRow.addView(temp,new LayoutParams(0,Ui.dp(getContext(),44),.65f));settingRow.addView(template,new LayoutParams(0,Ui.dp(getContext(),44),1.15f));Button apply=Ui.button(getContext(),"Apply & reload");apply.setOnClickListener(v->{String tmpl=template.getSelectedItemPosition()==1?"llama3":template.getSelectedItemPosition()==2?"plain":"chatml";ModelCatalog.saveSettings(repo,(int)parse(ctx.getText().toString()),(int)parse(max.getText().toString()),(int)parse(threads.getText().toString()),parseFloat(temp.getText().toString(),selected.temperature),tmpl);getContext().startForegroundService(new Intent(getContext(),WorldGeneratorService.class).setAction(WorldGeneratorService.ACTION_RELOAD_MODEL));Toast.makeText(getContext(),"Model settings applied",Toast.LENGTH_SHORT).show();});settingRow.addView(apply,new LayoutParams(Ui.dp(getContext(),145),Ui.dp(getContext(),42)));page.addView(settingRow,new LayoutParams(-1,Ui.dp(getContext(),46)));
        LinearLayout controls=new LinearLayout(getContext());controls.setOrientation(VERTICAL);LinearLayout row1=new LinearLayout(getContext()),row2=new LinearLayout(getContext());
        addAction(row1,"Start download",WorldGeneratorService.ACTION_DOWNLOAD);addAction(row1,"Stop download",WorldGeneratorService.ACTION_PAUSE_DOWNLOAD);addAction(row1,"Delete model",WorldGeneratorService.ACTION_DELETE_MODEL);
        addAction(row2,"Start generations",WorldGeneratorService.ACTION_START_GENERATION);addAction(row2,"Stop generations",WorldGeneratorService.ACTION_STOP_GENERATION);addAction(row2,"Generate now",WorldGeneratorService.ACTION_GENERATE_NOW);controls.addView(row1,new LayoutParams(-1,Ui.dp(getContext(),44)));controls.addView(row2,new LayoutParams(-1,Ui.dp(getContext(),44)));page.addView(controls,new LayoutParams(-1,Ui.dp(getContext(),90)));
        LinearLayout progressRow=new LinearLayout(getContext());progressRow.setGravity(Gravity.CENTER_VERTICAL);downloadLabel=Ui.text(getContext(),"AI model: waiting",13,Ui.TEXT);progressRow.addView(downloadLabel,new LayoutParams(Ui.dp(getContext(),300),Ui.dp(getContext(),34)));downloadProgress=new ProgressBar(getContext(),null,android.R.attr.progressBarStyleHorizontal);downloadProgress.setMax(1000);downloadProgress.setProgressTintList(ColorStateList.valueOf(Ui.CYAN));progressRow.addView(downloadProgress,new LayoutParams(0,Ui.dp(getContext(),18),1));page.addView(progressRow,new LayoutParams(-1,Ui.dp(getContext(),38)));
        LinearLayout cols=new LinearLayout(getContext());LinearLayout status=new LinearLayout(getContext());status.setOrientation(VERTICAL);LinearLayout stream=new LinearLayout(getContext());stream.setOrientation(VERTICAL);LinearLayout logs=new LinearLayout(getContext());logs.setOrientation(VERTICAL);
        TextView h=heading("LIVE GENERATOR",17);status.addView(h);addStatus(status,"generator","Generator");addStatus(status,"phase","Phase");addStatus(status,"active","Active job");addStatus(status,"model_bank","Model bank");addStatus(status,"forge_mode","Forge mode");addStatus(status,"forge_choice","Latest AI choice");addStatus(status,"result","Last result");addStatus(status,"runtime","Native runtime");addStatus(status,"profile","Runtime profile");addStatus(status,"speed","Live speed");addStatus(status,"catalog","Catalog");addStatus(status,"queue","Queue");addStatus(status,"ram","Free RAM");addStatus(status,"thermal","Thermal");
        streamHeader=heading("SAFE AI OUTPUT",17);stream.addView(streamHeader);stream.addView(subheading("PROMPT"));promptText=Ui.text(getContext(),"The exact generation prompt will appear here.",12,Ui.MUTED);promptText.setTextIsSelectable(true);stream.addView(promptText);stream.addView(subheading("CRASH-GUARDED MODEL OUTPUT"));outputText=Ui.text(getContext(),"Waiting for generation…",13,Ui.TEXT);outputText.setTextIsSelectable(true);outputText.setPadding(Ui.dp(getContext(),8),Ui.dp(getContext(),8),Ui.dp(getContext(),8),Ui.dp(getContext(),8));outputText.setBackground(Ui.round(Ui.PANEL,12,Ui.CYAN,1));stream.addView(outputText);
        logs.addView(heading("AI CONTENT MANAGER",17));creationList=new LinearLayout(getContext());creationList.setOrientation(VERTICAL);logs.addView(creationList);logs.addView(heading("ACCEPT / REJECT LOG",15));eventList=new LinearLayout(getContext());eventList.setOrientation(VERTICAL);logs.addView(eventList);
        ScrollView s1=new ScrollView(getContext());s1.addView(status);ScrollView s2=new ScrollView(getContext());s2.addView(stream);ScrollView s3=new ScrollView(getContext());s3.addView(logs);cols.addView(s1,new LayoutParams(0,-1,.85f));cols.addView(s2,new LayoutParams(0,-1,1.25f));cols.addView(s3,new LayoutParams(0,-1,1f));page.addView(cols,new LayoutParams(-1,0,1));lastStatsAt=0;lastListsAt=0;lastCreationSeq=Long.MIN_VALUE;updateAi(true);
    }

    private void addAction(LinearLayout row,String label,String action){Button b=Ui.button(getContext(),label);b.setOnClickListener(v->{getContext().startForegroundService(new Intent(getContext(),WorldGeneratorService.class).setAction(action));handler.postDelayed(()->updateAi(true),250);});LayoutParams lp=new LayoutParams(0,Ui.dp(getContext(),42),1);lp.setMargins(0,0,Ui.dp(getContext(),8),0);row.addView(b,lp);}
    private void addStatus(LinearLayout parent,String key,String label){TextView t=Ui.text(getContext(),label.toUpperCase()+"\n…",13,Ui.TEXT);t.setPadding(Ui.dp(getContext(),10),Ui.dp(getContext(),5),Ui.dp(getContext(),10),Ui.dp(getContext(),5));parent.addView(t);statusValues.put(key,t);}
    private void status(String key,String label,String value){TextView t=statusValues.get(key);if(t!=null)setIfChanged(t,label.toUpperCase()+"\n"+value);}

    private void updateAi(boolean force){if(selectedTab!=0||downloadLabel==null)return;long now=System.currentTimeMillis();long got=parse(repo.getState("download_bytes","0")),total=parse(repo.getState("download_total","-1"));String progress=total>0?(100*got/total)+"%  ("+(got/1048576)+" / "+(total/1048576)+" MiB)":(got/1048576)+" MiB";downloadProgress.setIndeterminate(total<=0&&got>0);if(total>0)downloadProgress.setProgress((int)Math.min(1000,1000*got/total));setIfChanged(downloadLabel,ModelCatalog.selected(repo).label+"  "+progress+"  •  "+repo.getState("model_status","press Start"));
        String tps=repo.getState("last_tps","0");setIfChanged(streamHeader,"SAFE AI OUTPUT • "+repo.getState("stream_pass","WAITING")+" • "+tps+" tok/s");setIfChanged(promptText,repo.getState("current_prompt","The exact generation prompt will appear here."));setIfChanged(outputText,repo.getState("stream_output","Waiting for generation…"));
        if(force||now-lastStatsAt>1800){JSONObject s=repo.stats();status("generator","Generator",Boolean.parseBoolean(repo.getState("generator_enabled","true"))?"RUNNING":"STOPPED");status("phase","Phase",repo.getState("generator_phase","idle"));status("active","Active job",repo.getState("active_job","idle"));List<ModelBank.ModelInfo> models=new ModelBank(getContext()).list();status("model_bank","Model bank",models.size()+" reusable GGUF file(s) • Documents/Infinite RPG/Models");status("forge_mode","Forge mode",repo.getState("forge_mode","required catalog first, then endless novelty"));status("forge_choice","Latest AI choice",repo.getState("forge_choice","waiting for required jobs"));status("result","Last result",repo.getState("last_result","none yet"));status("runtime","Native runtime",repo.getState("model_runtime","protected process / unloaded"));status("profile","Runtime profile",ModelCatalog.settingsSummary(repo));status("speed","Live speed",tps+" tokens/s");status("catalog","Catalog",s.optLong("content")+" total • "+s.optLong("ai")+" AI-created");status("queue","Queue",s.optLong("queued")+" queued • "+s.optLong("done")+" completed • "+s.optLong("rejected")+" rejected");ActivityManager.MemoryInfo mi=new ActivityManager.MemoryInfo();((ActivityManager)getContext().getSystemService(Context.ACTIVITY_SERVICE)).getMemoryInfo(mi);status("ram","Free RAM",(mi.availMem/1048576)+" MiB / "+(mi.totalMem/1048576)+" MiB");if(Build.VERSION.SDK_INT>=29){PowerManager pm=(PowerManager)getContext().getSystemService(Context.POWER_SERVICE);status("thermal","Thermal",thermal(pm.getCurrentThermalStatus()));}else status("thermal","Thermal","not reported");lastStatsAt=now;}
        long seq=parse(repo.getState("creation_seq","0"));if(force||seq!=lastCreationSeq){refreshCreations();lastCreationSeq=seq;}if(force||now-lastListsAt>5000){refreshEvents();lastListsAt=now;}
    }

    private void buildStream(){
        LinearLayout top=new LinearLayout(getContext());top.setGravity(Gravity.CENTER_VERTICAL);streamHeader=heading("LIVE MODEL TOKEN STREAM",18);top.addView(streamHeader,new LayoutParams(0,Ui.dp(getContext(),48),1));Button forge=Ui.button(getContext(),"Generate now");forge.setOnClickListener(v->getContext().startForegroundService(new Intent(getContext(),WorldGeneratorService.class).setAction(WorldGeneratorService.ACTION_GENERATE_NOW)));top.addView(forge,new LayoutParams(Ui.dp(getContext(),150),Ui.dp(getContext(),42)));page.addView(top,new LayoutParams(-1,Ui.dp(getContext(),50)));
        streamStatus=Ui.text(getContext(),"Waiting for generator telemetry…",13,Ui.TEXT);streamStatus.setPadding(Ui.dp(getContext(),12),Ui.dp(getContext(),8),Ui.dp(getContext(),12),Ui.dp(getContext(),8));streamStatus.setBackground(Ui.round(Ui.PANEL,12,Ui.CYAN,1));page.addView(streamStatus,new LayoutParams(-1,Ui.dp(getContext(),80)));
        LinearLayout panes=new LinearLayout(getContext());LinearLayout promptPane=new LinearLayout(getContext());promptPane.setOrientation(VERTICAL);promptPane.addView(subheading("EXACT ACTIVE PROMPT"));promptText=Ui.text(getContext(),"The exact prompt will appear when a pass starts.",13,Ui.MUTED);promptText.setTextIsSelectable(true);promptText.setPadding(Ui.dp(getContext(),10),Ui.dp(getContext(),8),Ui.dp(getContext(),10),Ui.dp(getContext(),12));ScrollView promptScroll=new ScrollView(getContext());promptScroll.addView(promptText);promptPane.addView(promptScroll,new LayoutParams(-1,0,1));
        LinearLayout outputPane=new LinearLayout(getContext());outputPane.setOrientation(VERTICAL);LinearLayout outputHead=new LinearLayout(getContext());outputHead.setGravity(Gravity.CENTER_VERTICAL);outputHead.addView(subheading("STREAMED MODEL OUTPUT • VIEW STAYS WHERE YOU PUT IT"),new LayoutParams(0,Ui.dp(getContext(),34),1));Button latest=Ui.button(getContext(),"↓ Latest");latest.setOnClickListener(v->{if(streamOutputScroll!=null)streamOutputScroll.post(()->streamOutputScroll.fullScroll(ScrollView.FOCUS_DOWN));});outputHead.addView(latest,new LayoutParams(Ui.dp(getContext(),105),Ui.dp(getContext(),34)));outputPane.addView(outputHead);outputText=Ui.text(getContext(),"Waiting for the selected model's first token…",15,Ui.TEXT);outputText.setTextIsSelectable(true);outputText.setPadding(Ui.dp(getContext(),12),Ui.dp(getContext(),10),Ui.dp(getContext(),12),Ui.dp(getContext(),14));outputText.setBackground(Ui.round(Ui.PANEL,12,Ui.CYAN,1));streamOutputScroll=new ScrollView(getContext());streamOutputScroll.setFillViewport(true);streamOutputScroll.addView(outputText);outputPane.addView(streamOutputScroll,new LayoutParams(-1,0,1));
        panes.addView(promptPane,new LayoutParams(0,-1,.85f));LayoutParams op=new LayoutParams(0,-1,1.45f);op.setMargins(Ui.dp(getContext(),12),0,0,0);panes.addView(outputPane,op);page.addView(panes,new LayoutParams(-1,0,1));updateStream();
    }

    private void updateStream(){if(selectedTab!=1||streamStatus==null)return;String tps=repo.getState("last_tps","0.0"),pass=repo.getState("stream_pass","WAITING"),status=repo.getState("stream_status","waiting"),tokens=repo.getState("stream_token_count","0");setIfChanged(streamHeader,"LIVE MODEL TOKEN STREAM • "+tps+" tok/s • "+ModelCatalog.selected(repo).label);setIfChanged(streamStatus,"STATUS  "+status+"\nPASS  "+pass+"   •   TOKENS  "+tokens+"   •   GENERATOR  "+(Boolean.parseBoolean(repo.getState("generator_enabled","false"))?"RUNNING":"STOPPED")+"\nPHASE  "+repo.getState("generator_phase","idle")+"   •   JOB  "+repo.getState("active_job","idle"));setIfChanged(promptText,repo.getState("current_prompt","The exact prompt will appear when a pass starts."));setIfChanged(outputText,repo.getState("stream_output","Waiting for the selected model's first token…"));}

    private void refreshCreations(){if(creationList==null)return;creationList.removeAllViews();List<ContentItem> made=repo.recentAi(100);if(made.isEmpty())creationList.addView(Ui.text(getContext(),"New accepted creations will appear here with previews.",13,Ui.MUTED));for(ContentItem item:made){boolean disabled=repo.isDisabled(item.type,item.identity);LinearLayout row=new LinearLayout(getContext());row.setGravity(Gravity.CENTER_VERTICAL);row.addView(new ItemIconView(getContext(),item),new LayoutParams(Ui.dp(getContext(),58),Ui.dp(getContext(),58)));TextView text=Ui.text(getContext(),item.type+"  •  "+item.name+(disabled?"  [DISABLED]":"")+"\n"+item.text("description","New world creation"),12,disabled?Ui.MUTED:Ui.TEXT);row.addView(text,new LayoutParams(0,Ui.dp(getContext(),66),1));Button toggle=Ui.button(getContext(),disabled?"Enable":"Disable");toggle.setOnClickListener(v->{repo.setDisabled(item.type,item.identity,!repo.isDisabled(item.type,item.identity));refreshCreations();});row.addView(toggle,new LayoutParams(Ui.dp(getContext(),88),Ui.dp(getContext(),40)));Button delete=Ui.button(getContext(),"Delete");delete.setOnClickListener(v->{repo.deleteGenerated(item.type,item.identity);refreshCreations();refreshEvents();});row.addView(delete,new LayoutParams(Ui.dp(getContext(),78),Ui.dp(getContext(),40)));creationList.addView(row,new LayoutParams(-1,Ui.dp(getContext(),69)));}}
    private void refreshEvents(){if(eventList==null)return;eventList.removeAllViews();for(String e:repo.recentEvents(40))eventList.addView(Ui.text(getContext(),e,12,e.startsWith("ACCEPT")?Ui.GREEN:e.startsWith("ERROR")||e.startsWith("REJECT")?Ui.GOLD:Ui.TEXT));}

    private void buildAudio(){
        LinearLayout controls=new LinearLayout(getContext());controls.setGravity(Gravity.CENTER_VERTICAL);musicToggle=Ui.text(getContext(),"MUSIC ENABLED",15,Ui.GREEN);musicToggle.setTypeface(null,1);controls.addView(musicToggle,new LayoutParams(0,Ui.dp(getContext(),46),1));Button toggle=Ui.button(getContext(),"Mute music");toggle.setOnClickListener(v->{boolean enabled=!Boolean.parseBoolean(repo.getState("music_enabled","true"));repo.putState("music_enabled",Boolean.toString(enabled));toggle.setText(enabled?"Mute music":"Unmute music");updateMusic();});controls.addView(toggle,new LayoutParams(Ui.dp(getContext(),145),Ui.dp(getContext(),42)));Button previous=Ui.button(getContext(),"Previous");previous.setOnClickListener(v->skipTrack(-1));controls.addView(previous,new LayoutParams(Ui.dp(getContext(),120),Ui.dp(getContext(),42)));Button next=Ui.button(getContext(),"Next track");next.setOnClickListener(v->skipTrack(1));controls.addView(next,new LayoutParams(Ui.dp(getContext(),135),Ui.dp(getContext(),42)));page.addView(controls,new LayoutParams(-1,Ui.dp(getContext(),50)));
        musicNow=Ui.text(getContext(),"NOW PLAYING\n…",19,Ui.GOLD);musicNow.setTypeface(null,1);page.addView(musicNow,new LayoutParams(-1,Ui.dp(getContext(),62)));
        LinearLayout volumeRow=new LinearLayout(getContext());volumeRow.setGravity(Gravity.CENTER_VERTICAL);volumeLabel=Ui.text(getContext(),"Volume",14,Ui.TEXT);volumeRow.addView(volumeLabel,new LayoutParams(Ui.dp(getContext(),145),Ui.dp(getContext(),38)));SeekBar volume=new SeekBar(getContext());volume.setMax(100);volume.setProgress((int)parse(repo.getState("music_volume","62")));volume.setProgressTintList(ColorStateList.valueOf(Ui.CYAN));volume.setOnSeekBarChangeListener(new SeekBar.OnSeekBarChangeListener(){public void onProgressChanged(SeekBar b,int value,boolean user){if(user){repo.putState("music_volume",Integer.toString(value));setIfChanged(volumeLabel,"Volume  "+value+"%");}}public void onStartTrackingTouch(SeekBar b){}public void onStopTrackingTouch(SeekBar b){}});volumeRow.addView(volume,new LayoutParams(0,Ui.dp(getContext(),38),1));page.addView(volumeRow,new LayoutParams(-1,Ui.dp(getContext(),42)));
        LinearLayout soundRow=new LinearLayout(getContext());soundRow.setGravity(Gravity.CENTER_VERTICAL);TextView soundLabel=Ui.text(getContext(),"AMBIENT SOUNDS",14,Ui.CYAN);soundRow.addView(soundLabel,new LayoutParams(Ui.dp(getContext(),170),Ui.dp(getContext(),42)));Button muteSounds=Ui.button(getContext(),Boolean.parseBoolean(repo.getState("sounds_enabled","true"))?"Mute sounds":"Unmute sounds");muteSounds.setOnClickListener(v->{boolean enabled=!Boolean.parseBoolean(repo.getState("sounds_enabled","true"));repo.putState("sounds_enabled",Boolean.toString(enabled));muteSounds.setText(enabled?"Mute sounds":"Unmute sounds");});soundRow.addView(muteSounds,new LayoutParams(Ui.dp(getContext(),145),Ui.dp(getContext(),40)));SeekBar sounds=new SeekBar(getContext());sounds.setMax(100);sounds.setProgress((int)parse(repo.getState("sounds_volume","58")));sounds.setProgressTintList(ColorStateList.valueOf(Ui.GREEN));sounds.setOnSeekBarChangeListener(new SeekBar.OnSeekBarChangeListener(){public void onProgressChanged(SeekBar b,int value,boolean user){if(user)repo.putState("sounds_volume",Integer.toString(value));}public void onStartTrackingTouch(SeekBar b){}public void onStopTrackingTouch(SeekBar b){}});soundRow.addView(sounds,new LayoutParams(0,Ui.dp(getContext(),38),1));page.addView(soundRow,new LayoutParams(-1,Ui.dp(getContext(),46)));
        TextView info=Ui.text(getContext(),"50 original exploration tracks • 30 new themes • 15 classic remixes • evolving A/B/C movements • automatic five-minute rotation • separate music and ambient controls",13,Ui.MUTED);page.addView(info,new LayoutParams(-1,Ui.dp(getContext(),38)));
        LinearLayout tracks=new LinearLayout(getContext());tracks.setOrientation(VERTICAL);List<ContentItem> library=repo.list("MUSIC",128);musicTrackCount=library.size();int n=1;for(ContentItem song:library){String voices=song.text("lead","melodic lead").replace('_',' ')+" + "+song.text("ensemble","orchestra").replace('_',' ')+" • "+song.text("percussion","rhythm").replace('_',' ');TextView card=Ui.text(getContext(),String.format(java.util.Locale.US,"%02d  %s%s\n%s\n%d BPM  •  %s  •  %s",n++,song.name,song.json.optBoolean("remixed",false)?"  [REMIX]":"",song.text("description","Infinite RPG exploration theme"),song.number("tempo",82),song.text("scale","dorian").replace('_',' '),voices),14,Ui.TEXT);card.setPadding(Ui.dp(getContext(),12),Ui.dp(getContext(),9),Ui.dp(getContext(),12),Ui.dp(getContext(),9));card.setBackground(Ui.round(Ui.PANEL,12,Ui.CYAN,1));LayoutParams cp=new LayoutParams(-1,Ui.dp(getContext(),96));cp.setMargins(0,0,0,Ui.dp(getContext(),7));tracks.addView(card,cp);}ScrollView scroll=new ScrollView(getContext());scroll.addView(tracks);page.addView(scroll,new LayoutParams(-1,0,1));updateMusic();
    }

    private void buildWorld(){page.addView(heading("DETERMINISTIC WORLD SAVES",19));double[] player=repo.loadPlayer();EditText name=new EditText(getContext());name.setText(repo.getState("world_name","Infinite RPG World"));name.setTextColor(Ui.TEXT);name.setHintTextColor(Ui.MUTED);name.setHint("World name");EditText seed=new EditText(getContext());seed.setText(Long.toString((long)player[4]));seed.setTextColor(Ui.TEXT);seed.setInputType(android.text.InputType.TYPE_CLASS_NUMBER|android.text.InputType.TYPE_NUMBER_FLAG_SIGNED);LinearLayout fields=new LinearLayout(getContext());fields.addView(name,new LayoutParams(0,Ui.dp(getContext(),48),1));fields.addView(seed,new LayoutParams(0,Ui.dp(getContext(),48),1));page.addView(fields);LinearLayout actions=new LinearLayout(getContext());Button save=Ui.button(getContext(),"Save current world");Button create=Ui.button(getContext(),"Create new from seed");actions.addView(save,new LayoutParams(0,Ui.dp(getContext(),44),1));actions.addView(create,new LayoutParams(0,Ui.dp(getContext(),44),1));page.addView(actions);LinearLayout saved=new LinearLayout(getContext());saved.setOrientation(VERTICAL);Runnable refresh=()->{saved.removeAllViews();saved.addView(heading("SAVED IN DOCUMENTS / INFINITE RPG",16));List<WorldSaveManager.SaveInfo> list=worldSaves.list();if(list.isEmpty())saved.addView(Ui.text(getContext(),"No exported worlds yet.",14,Ui.MUTED));for(WorldSaveManager.SaveInfo info:list){LinearLayout row=new LinearLayout(getContext());row.setGravity(Gravity.CENTER_VERTICAL);row.addView(Ui.text(getContext(),info.name+"\n"+new java.text.SimpleDateFormat("MMM d, yyyy  h:mm a",java.util.Locale.US).format(new java.util.Date(info.modified)),14,Ui.TEXT),new LayoutParams(0,Ui.dp(getContext(),58),1));Button load=Ui.button(getContext(),"Load");load.setOnClickListener(v->{if(worldSaves.load(info)){Toast.makeText(getContext(),"Loaded "+info.name,Toast.LENGTH_SHORT).show();onWorldChanged.run();}else Toast.makeText(getContext(),"World load failed",Toast.LENGTH_LONG).show();});row.addView(load,new LayoutParams(Ui.dp(getContext(),110),Ui.dp(getContext(),42)));saved.addView(row,new LayoutParams(-1,Ui.dp(getContext(),62)));}};save.setOnClickListener(v->{String result=worldSaves.save(name.getText().toString());Toast.makeText(getContext(),result,Toast.LENGTH_LONG).show();refresh.run();});create.setOnClickListener(v->{worldSaves.save(repo.getState("world_name","Infinite RPG World"));long value;try{value=Long.parseLong(seed.getText().toString());}catch(Exception e){value=System.currentTimeMillis();}repo.createNewWorld(name.getText().toString().trim().isEmpty()?"Infinite RPG World":name.getText().toString().trim(),value);worldSaves.save(repo.getState("world_name","Infinite RPG World"));onWorldChanged.run();});ScrollView scroll=new ScrollView(getContext());scroll.addView(saved);page.addView(scroll,new LayoutParams(-1,0,1));refresh.run();}

    private void skipTrack(int delta){long offset=parse(repo.getState("music_track_offset","0"));repo.putState("music_track_offset",Long.toString(offset+delta));handler.postDelayed(this::updateMusic,450);}
    private void updateMusic(){if(selectedTab!=2||musicNow==null)return;boolean enabled=Boolean.parseBoolean(repo.getState("music_enabled","true"));setIfChanged(musicToggle,enabled?"MUSIC ENABLED":"MUSIC PAUSED");musicToggle.setTextColor(enabled?Ui.GREEN:Ui.GOLD);setIfChanged(musicNow,"NOW PLAYING\n"+repo.getState("music_now","First Horizon")+"  •  track "+repo.getState("music_track_number","1")+" / "+musicTrackCount);setIfChanged(volumeLabel,"Volume  "+repo.getState("music_volume","62")+"%");}

    private void buildSettings(){
        page.addView(heading("GAME & PERFORMANCE",19));LinearLayout cards=new LinearLayout(getContext());cards.setOrientation(VERTICAL);addSetting(cards,"Exact placement","Choose a build, tap its exact world position, preview it, then explicitly Confirm or Cancel.",Ui.GREEN);addSetting(cards,"Deterministic worlds","Named worlds use stable seeds and export complete portable saves, including AI creations, to Documents/Infinite RPG.",Ui.CYAN);addSetting(cards,"Corrected animation","The player gait now adds planted-step sway and body travel. Every passive animal direction occupies one complete uncropped sprite cell.",Ui.TEXT);addSetting(cards,"Living environment","Trees, flowers, rocks, birds, ambient wildlife audio, weather, and enterable loot caves are generated around the world.",Ui.GOLD);addSetting(cards,"Persistent simulation","Position, inventory, chest contents, buildings, caves, animals, breeding state, AI content, and creation controls are saved.",Ui.TEXT);ScrollView scroll=new ScrollView(getContext());scroll.addView(cards);page.addView(scroll,new LayoutParams(-1,0,1));
    }
    private void addSetting(LinearLayout list,String title,String body,int color){TextView card=Ui.text(getContext(),title.toUpperCase()+"\n"+body,15,color);card.setPadding(Ui.dp(getContext(),14),Ui.dp(getContext(),12),Ui.dp(getContext(),14),Ui.dp(getContext(),12));card.setBackground(Ui.round(Ui.PANEL,14,Ui.CYAN,1));LayoutParams lp=new LayoutParams(-1,Ui.dp(getContext(),84));lp.setMargins(0,0,0,Ui.dp(getContext(),9));list.addView(card,lp);}

    private TextView heading(String value,int size){TextView t=Ui.text(getContext(),value,size,Ui.CYAN);t.setTypeface(null,1);return t;}
    private TextView subheading(String value){TextView t=Ui.text(getContext(),value,12,Ui.GOLD);t.setTypeface(null,1);return t;}
    private void setIfChanged(TextView view,String value){if(view!=null&&!value.contentEquals(view.getText()))view.setText(value);}
    private long parse(String value){try{return Long.parseLong(value);}catch(Exception e){return 0;}}
    private float parseFloat(String value,float fallback){try{return Float.parseFloat(value);}catch(Exception e){return fallback;}}
    private EditText numberField(String hint,String value){EditText e=new EditText(getContext());e.setHint(hint);e.setText(value);e.setSingleLine(true);e.setTextColor(Ui.TEXT);e.setHintTextColor(Ui.MUTED);e.setInputType(android.text.InputType.TYPE_CLASS_NUMBER|android.text.InputType.TYPE_NUMBER_FLAG_DECIMAL);return e;}
    private String thermal(int value){String[] a={"none","light","moderate","severe","critical","emergency","shutdown"};return a[Math.max(0,Math.min(a.length-1,value))];}
    @Override protected void onAttachedToWindow(){super.onAttachedToWindow();handler.post(tick);}
    @Override protected void onDetachedFromWindow(){handler.removeCallbacks(tick);super.onDetachedFromWindow();}
    private final Runnable tick=new Runnable(){@Override public void run(){if(selectedTab==0)updateAi(false);else if(selectedTab==1)updateStream();else if(selectedTab==2)updateMusic();handler.postDelayed(this,250);}};
}
