package app.infiniterpg.ai;

import org.json.JSONObject;
import app.infiniterpg.data.ContentRepository;
import java.util.Arrays;
import java.util.List;

/** Download choices plus the exact runtime/prompt profile used by each model. */
public final class ModelCatalog {
    public static final class Profile {
        public final String key,label,fileName,url,template,note;public final long minBytes;public final int context,maxTokens,threads;public final float temperature;
        Profile(String key,String label,String fileName,String url,long minBytes,int context,int maxTokens,int threads,float temperature,String template,String note){this.key=key;this.label=label;this.fileName=fileName;this.url=url;this.minBytes=minBytes;this.context=context;this.maxTokens=maxTokens;this.threads=threads;this.temperature=temperature;this.template=template;this.note=note;}
        public boolean isBankOnly(){return url==null||url.isEmpty();}
    }

    public static final Profile QWEN25=new Profile("qwen25_q8","Qwen2.5 0.5B Instruct Q8 • recommended","qwen2.5-0.5b-instruct-q8_0.gguf","https://huggingface.co/Qwen/Qwen2.5-0.5B-Instruct-GGUF/resolve/main/qwen2.5-0.5b-instruct-q8_0.gguf?download=true",620L*1024L*1024L,1280,420,1,.32f,"chatml","Best small preset for strict instructions and structured JSON.");
    public static final Profile QWEN3=new Profile("qwen3_q8","Qwen3 0.6B Q8 • current","Qwen3-0.6B-Q8_0.gguf","https://huggingface.co/unsloth/Qwen3-0.6B-GGUF/resolve/main/Qwen3-0.6B-Q8_0.gguf?download=true",580L*1024L*1024L,1280,420,1,.28f,"chatml","Current model; faster than the 1B choice but weaker at the catalog contract.");
    public static final Profile SMOL=new Profile("smollm2_q8","SmolLM2 360M Instruct Q8 • fastest","SmolLM2-360M-Instruct-Q8_0.gguf","https://huggingface.co/bartowski/SmolLM2-360M-Instruct-GGUF/resolve/main/SmolLM2-360M-Instruct-Q8_0.gguf?download=true",350L*1024L*1024L,1024,360,1,.25f,"chatml","Fastest and lightest preset; lower creativity and validation quality.");
    public static final Profile LLAMA=new Profile("llama32_1b_q4","Llama 3.2 1B Instruct Q4_K_M • strongest","Llama-3.2-1B-Instruct-Q4_K_M.gguf","https://huggingface.co/bartowski/Llama-3.2-1B-Instruct-GGUF/resolve/main/Llama-3.2-1B-Instruct-Q4_K_M.gguf?download=true",700L*1024L*1024L,1280,420,1,.35f,"llama3","Largest preset and likely strongest, but slower and heavier.");
    public static final List<Profile> PRESETS=Arrays.asList(QWEN25,QWEN3,SMOL,LLAMA);

    private ModelCatalog(){}
    public static Profile byKey(String key){for(Profile p:PRESETS)if(p.key.equals(key))return p;return null;}
    public static Profile selected(ContentRepository repo){String key=repo.getState("selected_model_key","qwen25_q8");Profile preset=byKey(key);if(preset!=null)return withSaved(repo,preset);String file=repo.getState("selected_model_file",key.startsWith("bank:")?key.substring(5):"imported.gguf");String label=repo.getState("selected_model_name","Imported: "+file);long size=parseLong(repo.getState("selected_model_min_bytes","20971520"),20971520);Profile custom=new Profile(key,label,file,"",Math.max(20L*1024L*1024L,size/2),1280,420,1,.30f,repo.getState("model_template","chatml"),"Imported GGUF from the Documents model bank.");return withSaved(repo,custom);}
    private static Profile withSaved(ContentRepository repo,Profile base){try{JSONObject s=new JSONObject(repo.getState("model_settings_"+safe(base.key),"{}"));return new Profile(base.key,base.label,base.fileName,base.url,base.minBytes,clamp(s.optInt("context",base.context),768,1536),clamp(s.optInt("max_tokens",base.maxTokens),128,460),clamp(s.optInt("threads",base.threads),1,2),(float)Math.max(.05,Math.min(1.2,s.optDouble("temperature",base.temperature))),s.optString("template",base.template),base.note);}catch(Exception ignored){return base;}}
    public static void select(ContentRepository repo,Profile p){Profile chosen=withSaved(repo,p);repo.putState("selected_model_key",chosen.key);repo.putState("selected_model_name",chosen.label);repo.putState("selected_model_file",chosen.fileName);repo.putState("model_context",Integer.toString(chosen.context));repo.putState("model_max_tokens",Integer.toString(chosen.maxTokens));repo.putState("model_threads",Integer.toString(chosen.threads));repo.putState("model_temperature",Float.toString(chosen.temperature));repo.putState("model_template",chosen.template);repo.putState("model_status","selected — check bank or press Start download");repo.putState("model_runtime","model switch pending");repo.putState("generator_enabled","false");repo.putState("generation_inflight","false");repo.putState("download_bytes","0");repo.putState("download_total","-1");}
    public static void selectBank(ContentRepository repo,String file,long bytes){String clean=ModelBank.cleanName(file);Profile p=new Profile("bank:"+clean,"Imported: "+clean,clean,"",Math.max(20L*1024L*1024L,bytes/2),1280,420,1,.30f,"chatml","Imported GGUF from Documents/Infinite RPG/Models.");select(repo,p);repo.putState("selected_model_min_bytes",Long.toString(bytes));repo.putState("model_status","banked model selected — press Start download to stage it");}
    public static void saveSettings(ContentRepository repo,int context,int maxTokens,int threads,float temperature,String template){Profile p=selected(repo);try{JSONObject s=new JSONObject().put("context",clamp(context,768,1536)).put("max_tokens",clamp(maxTokens,128,460)).put("threads",clamp(threads,1,2)).put("temperature",Math.max(.05,Math.min(1.2,temperature))).put("template",template);repo.putState("model_settings_"+safe(p.key),s.toString());repo.putState("model_context",Integer.toString(s.getInt("context")));repo.putState("model_max_tokens",Integer.toString(s.getInt("max_tokens")));repo.putState("model_threads",Integer.toString(s.getInt("threads")));repo.putState("model_temperature",Double.toString(s.getDouble("temperature")));repo.putState("model_template",template);repo.putState("model_runtime","settings changed — reload pending");}catch(Exception ignored){}}
    public static String wrapPrompt(ContentRepository repo,String prompt){Profile p=selected(repo);String template=repo.getState("model_template",p.template);String system="You are Infinite RPG's local game-content compiler. Obey the requested keys and types exactly. Produce one complete JSON object and no commentary.";if("llama3".equals(template))return "<|begin_of_text|><|start_header_id|>system<|end_header_id|>\n\n"+system+"<|eot_id|><|start_header_id|>user<|end_header_id|>\n\n"+prompt+"<|eot_id|><|start_header_id|>assistant<|end_header_id|>\n\n";if("plain".equals(template))return system+"\n\n"+prompt+"\n\nJSON:";return "<|im_start|>system\n"+system+"<|im_end|>\n<|im_start|>user\n"+prompt+"<|im_end|>\n<|im_start|>assistant\n";}
    public static String settingsSummary(ContentRepository repo){Profile p=selected(repo);return p.label+" • "+repo.getState("model_context",Integer.toString(p.context))+" ctx • "+repo.getState("model_max_tokens",Integer.toString(p.maxTokens))+" output • "+repo.getState("model_threads",Integer.toString(p.threads))+" thread • temp "+repo.getState("model_temperature",Float.toString(p.temperature))+" • "+repo.getState("model_template",p.template);}
    private static String safe(String key){return key.replaceAll("[^A-Za-z0-9_]","_");}
    private static int clamp(int v,int lo,int hi){return Math.max(lo,Math.min(hi,v));}
    private static long parseLong(String v,long fallback){try{return Long.parseLong(v);}catch(Exception e){return fallback;}}
}
